// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v2/config_service.proto

package apiv2

import (
	v2 "github.com/syncthing/syncthing/internal/config/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetConfigurationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetConfigurationRequest_builder) Build() *GetConfigurationRequest {
	m0 := &GetConfigurationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type WatchConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigurationRequest) Reset() {
	*x = WatchConfigurationRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigurationRequest) ProtoMessage() {}

func (x *WatchConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type WatchConfigurationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 WatchConfigurationRequest_builder) Build() *WatchConfigurationRequest {
	m0 := &WatchConfigurationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetConfigurationResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config *v2.Configuration      `protobuf:"bytes,1,opt,name=config"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetConfigurationResponse) GetConfig() *v2.Configuration {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *GetConfigurationResponse) SetConfig(v *v2.Configuration) {
	x.xxx_hidden_Config = v
}

func (x *GetConfigurationResponse) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *GetConfigurationResponse) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type GetConfigurationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Config *v2.Configuration
}

func (b0 GetConfigurationResponse_builder) Build() *GetConfigurationResponse {
	m0 := &GetConfigurationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Config = b.Config
	return m0
}

type UpdateOptionsRequest struct {
	state                 protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Options    *v2.OptionsConfiguration `protobuf:"bytes,1,opt,name=options"`
	xxx_hidden_UpdateMask *fieldmaskpb.FieldMask   `protobuf:"bytes,2,opt,name=update_mask,json=updateMask"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateOptionsRequest) Reset() {
	*x = UpdateOptionsRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOptionsRequest) ProtoMessage() {}

func (x *UpdateOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateOptionsRequest) GetOptions() *v2.OptionsConfiguration {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *UpdateOptionsRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_UpdateMask
	}
	return nil
}

func (x *UpdateOptionsRequest) SetOptions(v *v2.OptionsConfiguration) {
	x.xxx_hidden_Options = v
}

func (x *UpdateOptionsRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_UpdateMask = v
}

func (x *UpdateOptionsRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *UpdateOptionsRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateMask != nil
}

func (x *UpdateOptionsRequest) ClearOptions() {
	x.xxx_hidden_Options = nil
}

func (x *UpdateOptionsRequest) ClearUpdateMask() {
	x.xxx_hidden_UpdateMask = nil
}

type UpdateOptionsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Options    *v2.OptionsConfiguration
	UpdateMask *fieldmaskpb.FieldMask
}

func (b0 UpdateOptionsRequest_builder) Build() *UpdateOptionsRequest {
	m0 := &UpdateOptionsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Options = b.Options
	x.xxx_hidden_UpdateMask = b.UpdateMask
	return m0
}

type UpdateOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOptionsResponse) Reset() {
	*x = UpdateOptionsResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOptionsResponse) ProtoMessage() {}

func (x *UpdateOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateOptionsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateOptionsResponse_builder) Build() *UpdateOptionsResponse {
	m0 := &UpdateOptionsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AddDeviceRequest struct {
	state             protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Device *v2.DeviceConfiguration `protobuf:"bytes,1,opt,name=device"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddDeviceRequest) Reset() {
	*x = AddDeviceRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceRequest) ProtoMessage() {}

func (x *AddDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddDeviceRequest) GetDevice() *v2.DeviceConfiguration {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return nil
}

func (x *AddDeviceRequest) SetDevice(v *v2.DeviceConfiguration) {
	x.xxx_hidden_Device = v
}

func (x *AddDeviceRequest) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Device != nil
}

func (x *AddDeviceRequest) ClearDevice() {
	x.xxx_hidden_Device = nil
}

type AddDeviceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Device *v2.DeviceConfiguration
}

func (b0 AddDeviceRequest_builder) Build() *AddDeviceRequest {
	m0 := &AddDeviceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Device = b.Device
	return m0
}

type AddDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDeviceResponse) Reset() {
	*x = AddDeviceResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeviceResponse) ProtoMessage() {}

func (x *AddDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AddDeviceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AddDeviceResponse_builder) Build() *AddDeviceResponse {
	m0 := &AddDeviceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveDeviceRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeviceId    *string                `protobuf:"bytes,2,opt,name=device_id,json=deviceId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RemoveDeviceRequest) Reset() {
	*x = RemoveDeviceRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceRequest) ProtoMessage() {}

func (x *RemoveDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveDeviceRequest) GetDeviceId() string {
	if x != nil {
		if x.xxx_hidden_DeviceId != nil {
			return *x.xxx_hidden_DeviceId
		}
		return ""
	}
	return ""
}

func (x *RemoveDeviceRequest) SetDeviceId(v string) {
	x.xxx_hidden_DeviceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RemoveDeviceRequest) HasDeviceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RemoveDeviceRequest) ClearDeviceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeviceId = nil
}

type RemoveDeviceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeviceId *string
}

func (b0 RemoveDeviceRequest_builder) Build() *RemoveDeviceRequest {
	m0 := &RemoveDeviceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeviceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_DeviceId = b.DeviceId
	}
	return m0
}

type RemoveDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDeviceResponse) Reset() {
	*x = RemoveDeviceResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDeviceResponse) ProtoMessage() {}

func (x *RemoveDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveDeviceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveDeviceResponse_builder) Build() *RemoveDeviceResponse {
	m0 := &RemoveDeviceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UpdateDeviceRequest struct {
	state                 protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Device     *v2.DeviceConfiguration `protobuf:"bytes,1,opt,name=device"`
	xxx_hidden_UpdateMask *fieldmaskpb.FieldMask  `protobuf:"bytes,2,opt,name=update_mask,json=updateMask"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateDeviceRequest) GetDevice() *v2.DeviceConfiguration {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return nil
}

func (x *UpdateDeviceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_UpdateMask
	}
	return nil
}

func (x *UpdateDeviceRequest) SetDevice(v *v2.DeviceConfiguration) {
	x.xxx_hidden_Device = v
}

func (x *UpdateDeviceRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_UpdateMask = v
}

func (x *UpdateDeviceRequest) HasDevice() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Device != nil
}

func (x *UpdateDeviceRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateMask != nil
}

func (x *UpdateDeviceRequest) ClearDevice() {
	x.xxx_hidden_Device = nil
}

func (x *UpdateDeviceRequest) ClearUpdateMask() {
	x.xxx_hidden_UpdateMask = nil
}

type UpdateDeviceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Device     *v2.DeviceConfiguration
	UpdateMask *fieldmaskpb.FieldMask
}

func (b0 UpdateDeviceRequest_builder) Build() *UpdateDeviceRequest {
	m0 := &UpdateDeviceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Device = b.Device
	x.xxx_hidden_UpdateMask = b.UpdateMask
	return m0
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateDeviceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateDeviceResponse_builder) Build() *UpdateDeviceResponse {
	m0 := &UpdateDeviceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AddFolderRequest struct {
	state             protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Folder *v2.FolderConfiguration `protobuf:"bytes,1,opt,name=folder"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddFolderRequest) Reset() {
	*x = AddFolderRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFolderRequest) ProtoMessage() {}

func (x *AddFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddFolderRequest) GetFolder() *v2.FolderConfiguration {
	if x != nil {
		return x.xxx_hidden_Folder
	}
	return nil
}

func (x *AddFolderRequest) SetFolder(v *v2.FolderConfiguration) {
	x.xxx_hidden_Folder = v
}

func (x *AddFolderRequest) HasFolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Folder != nil
}

func (x *AddFolderRequest) ClearFolder() {
	x.xxx_hidden_Folder = nil
}

type AddFolderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Folder *v2.FolderConfiguration
}

func (b0 AddFolderRequest_builder) Build() *AddFolderRequest {
	m0 := &AddFolderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Folder = b.Folder
	return m0
}

type AddFolderResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFolderResponse) Reset() {
	*x = AddFolderResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFolderResponse) ProtoMessage() {}

func (x *AddFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AddFolderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AddFolderResponse_builder) Build() *AddFolderResponse {
	m0 := &AddFolderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RemoveFolderRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FolderId    *string                `protobuf:"bytes,1,opt,name=folder_id,json=folderId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RemoveFolderRequest) Reset() {
	*x = RemoveFolderRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFolderRequest) ProtoMessage() {}

func (x *RemoveFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemoveFolderRequest) GetFolderId() string {
	if x != nil {
		if x.xxx_hidden_FolderId != nil {
			return *x.xxx_hidden_FolderId
		}
		return ""
	}
	return ""
}

func (x *RemoveFolderRequest) SetFolderId(v string) {
	x.xxx_hidden_FolderId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RemoveFolderRequest) HasFolderId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RemoveFolderRequest) ClearFolderId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FolderId = nil
}

type RemoveFolderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FolderId *string
}

func (b0 RemoveFolderRequest_builder) Build() *RemoveFolderRequest {
	m0 := &RemoveFolderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FolderId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_FolderId = b.FolderId
	}
	return m0
}

type RemoveFolderResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFolderResponse) Reset() {
	*x = RemoveFolderResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFolderResponse) ProtoMessage() {}

func (x *RemoveFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RemoveFolderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RemoveFolderResponse_builder) Build() *RemoveFolderResponse {
	m0 := &RemoveFolderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UpdateFolderRequest struct {
	state                 protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Folder     *v2.FolderConfiguration `protobuf:"bytes,1,opt,name=folder"`
	xxx_hidden_UpdateMask *fieldmaskpb.FieldMask  `protobuf:"bytes,2,opt,name=update_mask,json=updateMask"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateFolderRequest) Reset() {
	*x = UpdateFolderRequest{}
	mi := &file_api_v2_config_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFolderRequest) ProtoMessage() {}

func (x *UpdateFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateFolderRequest) GetFolder() *v2.FolderConfiguration {
	if x != nil {
		return x.xxx_hidden_Folder
	}
	return nil
}

func (x *UpdateFolderRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.xxx_hidden_UpdateMask
	}
	return nil
}

func (x *UpdateFolderRequest) SetFolder(v *v2.FolderConfiguration) {
	x.xxx_hidden_Folder = v
}

func (x *UpdateFolderRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.xxx_hidden_UpdateMask = v
}

func (x *UpdateFolderRequest) HasFolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Folder != nil
}

func (x *UpdateFolderRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateMask != nil
}

func (x *UpdateFolderRequest) ClearFolder() {
	x.xxx_hidden_Folder = nil
}

func (x *UpdateFolderRequest) ClearUpdateMask() {
	x.xxx_hidden_UpdateMask = nil
}

type UpdateFolderRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Folder     *v2.FolderConfiguration
	UpdateMask *fieldmaskpb.FieldMask
}

func (b0 UpdateFolderRequest_builder) Build() *UpdateFolderRequest {
	m0 := &UpdateFolderRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Folder = b.Folder
	x.xxx_hidden_UpdateMask = b.UpdateMask
	return m0
}

type UpdateFolderResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFolderResponse) Reset() {
	*x = UpdateFolderResponse{}
	mi := &file_api_v2_config_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFolderResponse) ProtoMessage() {}

func (x *UpdateFolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_config_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UpdateFolderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UpdateFolderResponse_builder) Build() *UpdateFolderResponse {
	m0 := &UpdateFolderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_v2_config_service_proto protoreflect.FileDescriptor

const file_api_v2_config_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v2/config_service.proto\x12\x10syncthing.api.v2\x1a\x1dconfig/v2/configuration.proto\x1a$config/v2/device_configuration.proto\x1a$config/v2/folder_configuration.proto\x1a%config/v2/options_configuration.proto\x1a google/protobuf/field_mask.proto\x1a!google/protobuf/go_features.proto\"\x19\n" +
	"\x17GetConfigurationRequest\"\x1b\n" +
	"\x19WatchConfigurationRequest\"V\n" +
	"\x18GetConfigurationResponse\x12:\n" +
	"\x06config\x18\x01 \x01(\v2\".syncthing.config.v2.ConfigurationR\x06config\"\x98\x01\n" +
	"\x14UpdateOptionsRequest\x12C\n" +
	"\aoptions\x18\x01 \x01(\v2).syncthing.config.v2.OptionsConfigurationR\aoptions\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x17\n" +
	"\x15UpdateOptionsResponse\"T\n" +
	"\x10AddDeviceRequest\x12@\n" +
	"\x06device\x18\x01 \x01(\v2(.syncthing.config.v2.DeviceConfigurationR\x06device\"\x13\n" +
	"\x11AddDeviceResponse\"2\n" +
	"\x13RemoveDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x16\n" +
	"\x14RemoveDeviceResponse\"\x94\x01\n" +
	"\x13UpdateDeviceRequest\x12@\n" +
	"\x06device\x18\x01 \x01(\v2(.syncthing.config.v2.DeviceConfigurationR\x06device\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x16\n" +
	"\x14UpdateDeviceResponse\"T\n" +
	"\x10AddFolderRequest\x12@\n" +
	"\x06folder\x18\x01 \x01(\v2(.syncthing.config.v2.FolderConfigurationR\x06folder\"\x13\n" +
	"\x11AddFolderResponse\"2\n" +
	"\x13RemoveFolderRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\"\x16\n" +
	"\x14RemoveFolderResponse\"\x94\x01\n" +
	"\x13UpdateFolderRequest\x12@\n" +
	"\x06folder\x18\x01 \x01(\v2(.syncthing.config.v2.FolderConfigurationR\x06folder\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x16\n" +
	"\x14UpdateFolderResponse2\x8e\a\n" +
	"\x14ConfigurationService\x12k\n" +
	"\x10GetConfiguration\x12).syncthing.api.v2.GetConfigurationRequest\x1a*.syncthing.api.v2.GetConfigurationResponse\"\x00\x12q\n" +
	"\x12WatchConfiguration\x12+.syncthing.api.v2.WatchConfigurationRequest\x1a*.syncthing.api.v2.GetConfigurationResponse\"\x000\x01\x12b\n" +
	"\rUpdateOptions\x12&.syncthing.api.v2.UpdateOptionsRequest\x1a'.syncthing.api.v2.UpdateOptionsResponse\"\x00\x12V\n" +
	"\tAddDevice\x12\".syncthing.api.v2.AddDeviceRequest\x1a#.syncthing.api.v2.AddDeviceResponse\"\x00\x12_\n" +
	"\fRemoveDevice\x12%.syncthing.api.v2.RemoveDeviceRequest\x1a&.syncthing.api.v2.RemoveDeviceResponse\"\x00\x12_\n" +
	"\fUpdateDevice\x12%.syncthing.api.v2.UpdateDeviceRequest\x1a&.syncthing.api.v2.UpdateDeviceResponse\"\x00\x12V\n" +
	"\tAddFolder\x12\".syncthing.api.v2.AddFolderRequest\x1a#.syncthing.api.v2.AddFolderResponse\"\x00\x12_\n" +
	"\fRemoveFolder\x12%.syncthing.api.v2.RemoveFolderRequest\x1a&.syncthing.api.v2.RemoveFolderResponse\"\x00\x12_\n" +
	"\fUpdateFolder\x12%.syncthing.api.v2.UpdateFolderRequest\x1a&.syncthing.api.v2.UpdateFolderResponse\"\x00B\xca\x01\n" +
	"\x14com.syncthing.api.v2B\x12ConfigServiceProtoP\x01Z4github.com/syncthing/syncthing/internal/api/v2;apiv2\xa2\x02\x03SAX\xaa\x02\x10Syncthing.Api.V2\xca\x02\x10Syncthing\\Api\\V2\xe2\x02\x1cSyncthing\\Api\\V2\\GPBMetadata\xea\x02\x12Syncthing::Api::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_api_v2_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_v2_config_service_proto_goTypes = []any{
	(*GetConfigurationRequest)(nil),   // 0: syncthing.api.v2.GetConfigurationRequest
	(*WatchConfigurationRequest)(nil), // 1: syncthing.api.v2.WatchConfigurationRequest
	(*GetConfigurationResponse)(nil),  // 2: syncthing.api.v2.GetConfigurationResponse
	(*UpdateOptionsRequest)(nil),      // 3: syncthing.api.v2.UpdateOptionsRequest
	(*UpdateOptionsResponse)(nil),     // 4: syncthing.api.v2.UpdateOptionsResponse
	(*AddDeviceRequest)(nil),          // 5: syncthing.api.v2.AddDeviceRequest
	(*AddDeviceResponse)(nil),         // 6: syncthing.api.v2.AddDeviceResponse
	(*RemoveDeviceRequest)(nil),       // 7: syncthing.api.v2.RemoveDeviceRequest
	(*RemoveDeviceResponse)(nil),      // 8: syncthing.api.v2.RemoveDeviceResponse
	(*UpdateDeviceRequest)(nil),       // 9: syncthing.api.v2.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil),      // 10: syncthing.api.v2.UpdateDeviceResponse
	(*AddFolderRequest)(nil),          // 11: syncthing.api.v2.AddFolderRequest
	(*AddFolderResponse)(nil),         // 12: syncthing.api.v2.AddFolderResponse
	(*RemoveFolderRequest)(nil),       // 13: syncthing.api.v2.RemoveFolderRequest
	(*RemoveFolderResponse)(nil),      // 14: syncthing.api.v2.RemoveFolderResponse
	(*UpdateFolderRequest)(nil),       // 15: syncthing.api.v2.UpdateFolderRequest
	(*UpdateFolderResponse)(nil),      // 16: syncthing.api.v2.UpdateFolderResponse
	(*v2.Configuration)(nil),          // 17: syncthing.config.v2.Configuration
	(*v2.OptionsConfiguration)(nil),   // 18: syncthing.config.v2.OptionsConfiguration
	(*fieldmaskpb.FieldMask)(nil),     // 19: google.protobuf.FieldMask
	(*v2.DeviceConfiguration)(nil),    // 20: syncthing.config.v2.DeviceConfiguration
	(*v2.FolderConfiguration)(nil),    // 21: syncthing.config.v2.FolderConfiguration
}
var file_api_v2_config_service_proto_depIdxs = []int32{
	17, // 0: syncthing.api.v2.GetConfigurationResponse.config:type_name -> syncthing.config.v2.Configuration
	18, // 1: syncthing.api.v2.UpdateOptionsRequest.options:type_name -> syncthing.config.v2.OptionsConfiguration
	19, // 2: syncthing.api.v2.UpdateOptionsRequest.update_mask:type_name -> google.protobuf.FieldMask
	20, // 3: syncthing.api.v2.AddDeviceRequest.device:type_name -> syncthing.config.v2.DeviceConfiguration
	20, // 4: syncthing.api.v2.UpdateDeviceRequest.device:type_name -> syncthing.config.v2.DeviceConfiguration
	19, // 5: syncthing.api.v2.UpdateDeviceRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 6: syncthing.api.v2.AddFolderRequest.folder:type_name -> syncthing.config.v2.FolderConfiguration
	21, // 7: syncthing.api.v2.UpdateFolderRequest.folder:type_name -> syncthing.config.v2.FolderConfiguration
	19, // 8: syncthing.api.v2.UpdateFolderRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 9: syncthing.api.v2.ConfigurationService.GetConfiguration:input_type -> syncthing.api.v2.GetConfigurationRequest
	1,  // 10: syncthing.api.v2.ConfigurationService.WatchConfiguration:input_type -> syncthing.api.v2.WatchConfigurationRequest
	3,  // 11: syncthing.api.v2.ConfigurationService.UpdateOptions:input_type -> syncthing.api.v2.UpdateOptionsRequest
	5,  // 12: syncthing.api.v2.ConfigurationService.AddDevice:input_type -> syncthing.api.v2.AddDeviceRequest
	7,  // 13: syncthing.api.v2.ConfigurationService.RemoveDevice:input_type -> syncthing.api.v2.RemoveDeviceRequest
	9,  // 14: syncthing.api.v2.ConfigurationService.UpdateDevice:input_type -> syncthing.api.v2.UpdateDeviceRequest
	11, // 15: syncthing.api.v2.ConfigurationService.AddFolder:input_type -> syncthing.api.v2.AddFolderRequest
	13, // 16: syncthing.api.v2.ConfigurationService.RemoveFolder:input_type -> syncthing.api.v2.RemoveFolderRequest
	15, // 17: syncthing.api.v2.ConfigurationService.UpdateFolder:input_type -> syncthing.api.v2.UpdateFolderRequest
	2,  // 18: syncthing.api.v2.ConfigurationService.GetConfiguration:output_type -> syncthing.api.v2.GetConfigurationResponse
	2,  // 19: syncthing.api.v2.ConfigurationService.WatchConfiguration:output_type -> syncthing.api.v2.GetConfigurationResponse
	4,  // 20: syncthing.api.v2.ConfigurationService.UpdateOptions:output_type -> syncthing.api.v2.UpdateOptionsResponse
	6,  // 21: syncthing.api.v2.ConfigurationService.AddDevice:output_type -> syncthing.api.v2.AddDeviceResponse
	8,  // 22: syncthing.api.v2.ConfigurationService.RemoveDevice:output_type -> syncthing.api.v2.RemoveDeviceResponse
	10, // 23: syncthing.api.v2.ConfigurationService.UpdateDevice:output_type -> syncthing.api.v2.UpdateDeviceResponse
	12, // 24: syncthing.api.v2.ConfigurationService.AddFolder:output_type -> syncthing.api.v2.AddFolderResponse
	14, // 25: syncthing.api.v2.ConfigurationService.RemoveFolder:output_type -> syncthing.api.v2.RemoveFolderResponse
	16, // 26: syncthing.api.v2.ConfigurationService.UpdateFolder:output_type -> syncthing.api.v2.UpdateFolderResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v2_config_service_proto_init() }
func file_api_v2_config_service_proto_init() {
	if File_api_v2_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_config_service_proto_rawDesc), len(file_api_v2_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v2_config_service_proto_goTypes,
		DependencyIndexes: file_api_v2_config_service_proto_depIdxs,
		MessageInfos:      file_api_v2_config_service_proto_msgTypes,
	}.Build()
	File_api_v2_config_service_proto = out.File
	file_api_v2_config_service_proto_goTypes = nil
	file_api_v2_config_service_proto_depIdxs = nil
}
