changelog:
  categories:
    - title: Fixes
      labels:
        - bug

    - title: Features
      labels:
        - enhancement

    - title: Other
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
