// @generated by protoc-gen-es v2.2.5
// @generated from file discoproto/local.proto (package discoproto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file discoproto/local.proto.
 */
export declare const file_discoproto_local: GenFile;

/**
 * @generated from message discoproto.Announce
 */
export declare type Announce = Message<"discoproto.Announce"> & {
  /**
   * @generated from field: bytes id = 1;
   */
  id: Uint8Array;

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[];

  /**
   * @generated from field: int64 instance_id = 3;
   */
  instanceId: bigint;
};

/**
 * Describes the message discoproto.Announce.
 * Use `create(AnnounceSchema)` to create a new message.
 */
export declare const AnnounceSchema: GenMessage<Announce>;

