// @generated by protoc-gen-es v2.2.5
// @generated from file apiproto/tokenset.proto (package apiproto, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file apiproto/tokenset.proto.
 */
export const file_apiproto_tokenset = /*@__PURE__*/
  fileDesc("ChdhcGlwcm90by90b2tlbnNldC5wcm90bxIIYXBpcHJvdG8iaQoIVG9rZW5TZXQSLgoGdG9rZW5zGAEgAygLMh4uYXBpcHJvdG8uVG9rZW5TZXQuVG9rZW5zRW50cnkaLQoLVG9rZW5zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgDOgI4AUKTAQoMY29tLmFwaXByb3RvQg1Ub2tlbnNldFByb3RvUAFaNGdpdGh1Yi5jb20vc3luY3RoaW5nL3N5bmN0aGluZy9pbnRlcm5hbC9nZW4vYXBpcHJvdG+iAgNBWFiqAghBcGlwcm90b8oCCEFwaXByb3Rv4gIUQXBpcHJvdG9cR1BCTWV0YWRhdGHqAghBcGlwcm90b2IGcHJvdG8z");

/**
 * Describes the message apiproto.TokenSet.
 * Use `create(TokenSetSchema)` to create a new message.
 */
export const TokenSetSchema = /*@__PURE__*/
  messageDesc(file_apiproto_tokenset, 0);

