// @generated by protoc-gen-es v2.2.5
// @generated from file apiproto/tokenset.proto (package apiproto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apiproto/tokenset.proto.
 */
export declare const file_apiproto_tokenset: GenFile;

/**
 * @generated from message apiproto.TokenSet
 */
export declare type TokenSet = Message<"apiproto.TokenSet"> & {
  /**
   * token -> expiry time (epoch nanoseconds)
   *
   * @generated from field: map<string, int64> tokens = 1;
   */
  tokens: { [key: string]: bigint };
};

/**
 * Describes the message apiproto.TokenSet.
 * Use `create(TokenSetSchema)` to create a new message.
 */
export declare const TokenSetSchema: GenMessage<TokenSet>;

