// @generated by protoc-gen-es v2.2.5
// @generated from file discosrv/discosrv.proto (package discosrv, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file discosrv/discosrv.proto.
 */
export const file_discosrv_discosrv = /*@__PURE__*/
  fileDesc("ChdkaXNjb3Nydi9kaXNjb3Nydi5wcm90bxIIZGlzY29zcnYiTAoORGF0YWJhc2VSZWNvcmQSLAoJYWRkcmVzc2VzGAEgAygLMhkuZGlzY29zcnYuRGF0YWJhc2VBZGRyZXNzEgwKBHNlZW4YAyABKAMiXAoRUmVwbGljYXRpb25SZWNvcmQSCwoDa2V5GAEgASgMEiwKCWFkZHJlc3NlcxgCIAMoCzIZLmRpc2Nvc3J2LkRhdGFiYXNlQWRkcmVzcxIMCgRzZWVuGAMgASgDIjMKD0RhdGFiYXNlQWRkcmVzcxIPCgdhZGRyZXNzGAEgASgJEg8KB2V4cGlyZXMYAiABKANCkwEKDGNvbS5kaXNjb3NydkINRGlzY29zcnZQcm90b1ABWjRnaXRodWIuY29tL3N5bmN0aGluZy9zeW5jdGhpbmcvaW50ZXJuYWwvZ2VuL2Rpc2Nvc3J2ogIDRFhYqgIIRGlzY29zcnbKAghEaXNjb3NyduICFERpc2Nvc3J2XEdQQk1ldGFkYXRh6gIIRGlzY29zcnZiBnByb3RvMw");

/**
 * Describes the message discosrv.DatabaseRecord.
 * Use `create(DatabaseRecordSchema)` to create a new message.
 */
export const DatabaseRecordSchema = /*@__PURE__*/
  messageDesc(file_discosrv_discosrv, 0);

/**
 * Describes the message discosrv.ReplicationRecord.
 * Use `create(ReplicationRecordSchema)` to create a new message.
 */
export const ReplicationRecordSchema = /*@__PURE__*/
  messageDesc(file_discosrv_discosrv, 1);

/**
 * Describes the message discosrv.DatabaseAddress.
 * Use `create(DatabaseAddressSchema)` to create a new message.
 */
export const DatabaseAddressSchema = /*@__PURE__*/
  messageDesc(file_discosrv_discosrv, 2);

