// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v2/device_configuration.proto

package configv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_METADATA    Compression = 1
	Compression_COMPRESSION_NEVER       Compression = 2
	Compression_COMPRESSION_ALWAYS      Compression = 3
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_METADATA",
		2: "COMPRESSION_NEVER",
		3: "COMPRESSION_ALWAYS",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_METADATA":    1,
		"COMPRESSION_NEVER":       2,
		"COMPRESSION_ALWAYS":      3,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_config_v2_device_configuration_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_config_v2_device_configuration_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DeviceConfiguration struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeviceId                 *string                `protobuf:"bytes,1,opt,name=device_id,json=deviceId"`
	xxx_hidden_Enabled                  bool                   `protobuf:"varint,2,opt,name=enabled,def=1"`
	xxx_hidden_Name                     *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Addresses                *URLs                  `protobuf:"bytes,4,opt,name=addresses"`
	xxx_hidden_Compression              Compression            `protobuf:"varint,5,opt,name=compression,enum=syncthing.config.v2.Compression,def=1"`
	xxx_hidden_CertificateCommonName    *string                `protobuf:"bytes,6,opt,name=certificate_common_name,json=certificateCommonName,def=syncthing"`
	xxx_hidden_Introducer               bool                   `protobuf:"varint,7,opt,name=introducer"`
	xxx_hidden_SkipIntroductionRemovals bool                   `protobuf:"varint,8,opt,name=skip_introduction_removals,json=skipIntroductionRemovals"`
	xxx_hidden_IntroducedBy             *string                `protobuf:"bytes,9,opt,name=introduced_by,json=introducedBy"`
	xxx_hidden_AllowedNetworks          []string               `protobuf:"bytes,10,rep,name=allowed_networks,json=allowedNetworks"`
	xxx_hidden_AutoAcceptFolders        bool                   `protobuf:"varint,11,opt,name=auto_accept_folders,json=autoAcceptFolders"`
	xxx_hidden_RateLimits               *RateLimits            `protobuf:"bytes,12,opt,name=rate_limits,json=rateLimits"`
	xxx_hidden_MaxRequestKib            int32                  `protobuf:"varint,13,opt,name=max_request_kib,json=maxRequestKib,def=32768"`
	xxx_hidden_Untrusted                bool                   `protobuf:"varint,14,opt,name=untrusted"`
	xxx_hidden_RemoteGuiPort            int32                  `protobuf:"varint,15,opt,name=remote_gui_port,json=remoteGuiPort"`
	xxx_hidden_NumConnections           int32                  `protobuf:"varint,16,opt,name=num_connections,json=numConnections,def=3"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

// Default values for DeviceConfiguration fields.
const (
	Default_DeviceConfiguration_Enabled               = bool(true)
	Default_DeviceConfiguration_Compression           = Compression_COMPRESSION_METADATA
	Default_DeviceConfiguration_CertificateCommonName = string("syncthing")
	Default_DeviceConfiguration_MaxRequestKib         = int32(32768)
	Default_DeviceConfiguration_NumConnections        = int32(3)
)

func (x *DeviceConfiguration) Reset() {
	*x = DeviceConfiguration{}
	mi := &file_config_v2_device_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceConfiguration) ProtoMessage() {}

func (x *DeviceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_device_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeviceConfiguration) GetDeviceId() string {
	if x != nil {
		if x.xxx_hidden_DeviceId != nil {
			return *x.xxx_hidden_DeviceId
		}
		return ""
	}
	return ""
}

func (x *DeviceConfiguration) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_DeviceConfiguration_Enabled
}

func (x *DeviceConfiguration) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DeviceConfiguration) GetAddresses() *URLs {
	if x != nil {
		return x.xxx_hidden_Addresses
	}
	return nil
}

func (x *DeviceConfiguration) GetCompression() Compression {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Compression
		}
	}
	return Default_DeviceConfiguration_Compression
}

func (x *DeviceConfiguration) GetCertificateCommonName() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			if x.xxx_hidden_CertificateCommonName != nil {
				return *x.xxx_hidden_CertificateCommonName
			}
			return Default_DeviceConfiguration_CertificateCommonName
		}
	}
	return Default_DeviceConfiguration_CertificateCommonName
}

func (x *DeviceConfiguration) GetIntroducer() bool {
	if x != nil {
		return x.xxx_hidden_Introducer
	}
	return false
}

func (x *DeviceConfiguration) GetSkipIntroductionRemovals() bool {
	if x != nil {
		return x.xxx_hidden_SkipIntroductionRemovals
	}
	return false
}

func (x *DeviceConfiguration) GetIntroducedBy() string {
	if x != nil {
		if x.xxx_hidden_IntroducedBy != nil {
			return *x.xxx_hidden_IntroducedBy
		}
		return ""
	}
	return ""
}

func (x *DeviceConfiguration) GetAllowedNetworks() []string {
	if x != nil {
		return x.xxx_hidden_AllowedNetworks
	}
	return nil
}

func (x *DeviceConfiguration) GetAutoAcceptFolders() bool {
	if x != nil {
		return x.xxx_hidden_AutoAcceptFolders
	}
	return false
}

func (x *DeviceConfiguration) GetRateLimits() *RateLimits {
	if x != nil {
		return x.xxx_hidden_RateLimits
	}
	return nil
}

func (x *DeviceConfiguration) GetMaxRequestKib() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 12) {
			return x.xxx_hidden_MaxRequestKib
		}
	}
	return Default_DeviceConfiguration_MaxRequestKib
}

func (x *DeviceConfiguration) GetUntrusted() bool {
	if x != nil {
		return x.xxx_hidden_Untrusted
	}
	return false
}

func (x *DeviceConfiguration) GetRemoteGuiPort() int32 {
	if x != nil {
		return x.xxx_hidden_RemoteGuiPort
	}
	return 0
}

func (x *DeviceConfiguration) GetNumConnections() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 15) {
			return x.xxx_hidden_NumConnections
		}
	}
	return Default_DeviceConfiguration_NumConnections
}

func (x *DeviceConfiguration) SetDeviceId(v string) {
	x.xxx_hidden_DeviceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 16)
}

func (x *DeviceConfiguration) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 16)
}

func (x *DeviceConfiguration) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 16)
}

func (x *DeviceConfiguration) SetAddresses(v *URLs) {
	x.xxx_hidden_Addresses = v
}

func (x *DeviceConfiguration) SetCompression(v Compression) {
	x.xxx_hidden_Compression = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 16)
}

func (x *DeviceConfiguration) SetCertificateCommonName(v string) {
	x.xxx_hidden_CertificateCommonName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 16)
}

func (x *DeviceConfiguration) SetIntroducer(v bool) {
	x.xxx_hidden_Introducer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 16)
}

func (x *DeviceConfiguration) SetSkipIntroductionRemovals(v bool) {
	x.xxx_hidden_SkipIntroductionRemovals = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 16)
}

func (x *DeviceConfiguration) SetIntroducedBy(v string) {
	x.xxx_hidden_IntroducedBy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 16)
}

func (x *DeviceConfiguration) SetAllowedNetworks(v []string) {
	x.xxx_hidden_AllowedNetworks = v
}

func (x *DeviceConfiguration) SetAutoAcceptFolders(v bool) {
	x.xxx_hidden_AutoAcceptFolders = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 16)
}

func (x *DeviceConfiguration) SetRateLimits(v *RateLimits) {
	x.xxx_hidden_RateLimits = v
}

func (x *DeviceConfiguration) SetMaxRequestKib(v int32) {
	x.xxx_hidden_MaxRequestKib = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 16)
}

func (x *DeviceConfiguration) SetUntrusted(v bool) {
	x.xxx_hidden_Untrusted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 16)
}

func (x *DeviceConfiguration) SetRemoteGuiPort(v int32) {
	x.xxx_hidden_RemoteGuiPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 16)
}

func (x *DeviceConfiguration) SetNumConnections(v int32) {
	x.xxx_hidden_NumConnections = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 16)
}

func (x *DeviceConfiguration) HasDeviceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeviceConfiguration) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeviceConfiguration) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DeviceConfiguration) HasAddresses() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Addresses != nil
}

func (x *DeviceConfiguration) HasCompression() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *DeviceConfiguration) HasCertificateCommonName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DeviceConfiguration) HasIntroducer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *DeviceConfiguration) HasSkipIntroductionRemovals() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *DeviceConfiguration) HasIntroducedBy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *DeviceConfiguration) HasAutoAcceptFolders() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *DeviceConfiguration) HasRateLimits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RateLimits != nil
}

func (x *DeviceConfiguration) HasMaxRequestKib() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *DeviceConfiguration) HasUntrusted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *DeviceConfiguration) HasRemoteGuiPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *DeviceConfiguration) HasNumConnections() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *DeviceConfiguration) ClearDeviceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DeviceId = nil
}

func (x *DeviceConfiguration) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *DeviceConfiguration) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *DeviceConfiguration) ClearAddresses() {
	x.xxx_hidden_Addresses = nil
}

func (x *DeviceConfiguration) ClearCompression() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

func (x *DeviceConfiguration) ClearCertificateCommonName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

func (x *DeviceConfiguration) ClearIntroducer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Introducer = false
}

func (x *DeviceConfiguration) ClearSkipIntroductionRemovals() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_SkipIntroductionRemovals = false
}

func (x *DeviceConfiguration) ClearIntroducedBy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_IntroducedBy = nil
}

func (x *DeviceConfiguration) ClearAutoAcceptFolders() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_AutoAcceptFolders = false
}

func (x *DeviceConfiguration) ClearRateLimits() {
	x.xxx_hidden_RateLimits = nil
}

func (x *DeviceConfiguration) ClearMaxRequestKib() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
}

func (x *DeviceConfiguration) ClearUntrusted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Untrusted = false
}

func (x *DeviceConfiguration) ClearRemoteGuiPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_RemoteGuiPort = 0
}

func (x *DeviceConfiguration) ClearNumConnections() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
}

type DeviceConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeviceId                 *string
	Enabled                  *bool
	Name                     *string
	Addresses                *URLs
	Compression              *Compression
	CertificateCommonName    *string
	Introducer               *bool
	SkipIntroductionRemovals *bool
	IntroducedBy             *string
	AllowedNetworks          []string
	AutoAcceptFolders        *bool
	RateLimits               *RateLimits
	MaxRequestKib            *int32
	Untrusted                *bool
	RemoteGuiPort            *int32
	NumConnections           *int32
}

func (b0 DeviceConfiguration_builder) Build() *DeviceConfiguration {
	m0 := &DeviceConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DeviceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 16)
		x.xxx_hidden_DeviceId = b.DeviceId
	}
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 16)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 16)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Addresses = b.Addresses
	if b.Compression != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 16)
		x.xxx_hidden_Compression = *b.Compression
	}
	if b.CertificateCommonName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 16)
		x.xxx_hidden_CertificateCommonName = b.CertificateCommonName
	}
	if b.Introducer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 16)
		x.xxx_hidden_Introducer = *b.Introducer
	}
	if b.SkipIntroductionRemovals != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 16)
		x.xxx_hidden_SkipIntroductionRemovals = *b.SkipIntroductionRemovals
	}
	if b.IntroducedBy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 16)
		x.xxx_hidden_IntroducedBy = b.IntroducedBy
	}
	x.xxx_hidden_AllowedNetworks = b.AllowedNetworks
	if b.AutoAcceptFolders != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 16)
		x.xxx_hidden_AutoAcceptFolders = *b.AutoAcceptFolders
	}
	x.xxx_hidden_RateLimits = b.RateLimits
	if b.MaxRequestKib != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 16)
		x.xxx_hidden_MaxRequestKib = *b.MaxRequestKib
	}
	if b.Untrusted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 16)
		x.xxx_hidden_Untrusted = *b.Untrusted
	}
	if b.RemoteGuiPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 16)
		x.xxx_hidden_RemoteGuiPort = *b.RemoteGuiPort
	}
	if b.NumConnections != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 16)
		x.xxx_hidden_NumConnections = *b.NumConnections
	}
	return m0
}

var File_config_v2_device_configuration_proto protoreflect.FileDescriptor

const file_config_v2_device_configuration_proto_rawDesc = "" +
	"\n" +
	"$config/v2/device_configuration.proto\x12\x13syncthing.config.v2\x1a%config/v2/options_configuration.proto\x1a!google/protobuf/go_features.proto\"\xfd\x05\n" +
	"\x13DeviceConfiguration\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1e\n" +
	"\aenabled\x18\x02 \x01(\b:\x04trueR\aenabled\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x127\n" +
	"\taddresses\x18\x04 \x01(\v2\x19.syncthing.config.v2.URLsR\taddresses\x12X\n" +
	"\vcompression\x18\x05 \x01(\x0e2 .syncthing.config.v2.Compression:\x14COMPRESSION_METADATAR\vcompression\x12A\n" +
	"\x17certificate_common_name\x18\x06 \x01(\t:\tsyncthingR\x15certificateCommonName\x12\x1e\n" +
	"\n" +
	"introducer\x18\a \x01(\bR\n" +
	"introducer\x12<\n" +
	"\x1askip_introduction_removals\x18\b \x01(\bR\x18skipIntroductionRemovals\x12#\n" +
	"\rintroduced_by\x18\t \x01(\tR\fintroducedBy\x12)\n" +
	"\x10allowed_networks\x18\n" +
	" \x03(\tR\x0fallowedNetworks\x12.\n" +
	"\x13auto_accept_folders\x18\v \x01(\bR\x11autoAcceptFolders\x12@\n" +
	"\vrate_limits\x18\f \x01(\v2\x1f.syncthing.config.v2.RateLimitsR\n" +
	"rateLimits\x12-\n" +
	"\x0fmax_request_kib\x18\r \x01(\x05:\x0532768R\rmaxRequestKib\x12\x1c\n" +
	"\tuntrusted\x18\x0e \x01(\bR\tuntrusted\x12&\n" +
	"\x0fremote_gui_port\x18\x0f \x01(\x05R\rremoteGuiPort\x12*\n" +
	"\x0fnum_connections\x18\x10 \x01(\x05:\x013R\x0enumConnections*s\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMPRESSION_METADATA\x10\x01\x12\x15\n" +
	"\x11COMPRESSION_NEVER\x10\x02\x12\x16\n" +
	"\x12COMPRESSION_ALWAYS\x10\x03B\xe5\x01\n" +
	"\x17com.syncthing.config.v2B\x18DeviceConfigurationProtoP\x01Z:github.com/syncthing/syncthing/internal/config/v2;configv2\xa2\x02\x03SCX\xaa\x02\x13Syncthing.Config.V2\xca\x02\x13Syncthing\\Config\\V2\xe2\x02\x1fSyncthing\\Config\\V2\\GPBMetadata\xea\x02\x15Syncthing::Config::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v2_device_configuration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_config_v2_device_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_v2_device_configuration_proto_goTypes = []any{
	(Compression)(0),            // 0: syncthing.config.v2.Compression
	(*DeviceConfiguration)(nil), // 1: syncthing.config.v2.DeviceConfiguration
	(*URLs)(nil),                // 2: syncthing.config.v2.URLs
	(*RateLimits)(nil),          // 3: syncthing.config.v2.RateLimits
}
var file_config_v2_device_configuration_proto_depIdxs = []int32{
	2, // 0: syncthing.config.v2.DeviceConfiguration.addresses:type_name -> syncthing.config.v2.URLs
	0, // 1: syncthing.config.v2.DeviceConfiguration.compression:type_name -> syncthing.config.v2.Compression
	3, // 2: syncthing.config.v2.DeviceConfiguration.rate_limits:type_name -> syncthing.config.v2.RateLimits
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_v2_device_configuration_proto_init() }
func file_config_v2_device_configuration_proto_init() {
	if File_config_v2_device_configuration_proto != nil {
		return
	}
	file_config_v2_options_configuration_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v2_device_configuration_proto_rawDesc), len(file_config_v2_device_configuration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v2_device_configuration_proto_goTypes,
		DependencyIndexes: file_config_v2_device_configuration_proto_depIdxs,
		EnumInfos:         file_config_v2_device_configuration_proto_enumTypes,
		MessageInfos:      file_config_v2_device_configuration_proto_msgTypes,
	}.Build()
	File_config_v2_device_configuration_proto = out.File
	file_config_v2_device_configuration_proto_goTypes = nil
	file_config_v2_device_configuration_proto_depIdxs = nil
}
