// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v2/options_configuration.proto

package configv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionsConfiguration struct {
	state                     protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_General        *OptionsConfiguration_General        `protobuf:"bytes,1,opt,name=general"`
	xxx_hidden_Network        *OptionsConfiguration_Network        `protobuf:"bytes,2,opt,name=network"`
	xxx_hidden_AutoUpgrade    *OptionsConfiguration_AutoUpgrade    `protobuf:"bytes,3,opt,name=auto_upgrade,json=autoUpgrade"`
	xxx_hidden_UsageReporting *OptionsConfiguration_UsageReporting `protobuf:"bytes,4,opt,name=usage_reporting,json=usageReporting"`
	xxx_hidden_Audit          *OptionsConfiguration_Audit          `protobuf:"bytes,5,opt,name=audit"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OptionsConfiguration) Reset() {
	*x = OptionsConfiguration{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration) ProtoMessage() {}

func (x *OptionsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration) GetGeneral() *OptionsConfiguration_General {
	if x != nil {
		return x.xxx_hidden_General
	}
	return nil
}

func (x *OptionsConfiguration) GetNetwork() *OptionsConfiguration_Network {
	if x != nil {
		return x.xxx_hidden_Network
	}
	return nil
}

func (x *OptionsConfiguration) GetAutoUpgrade() *OptionsConfiguration_AutoUpgrade {
	if x != nil {
		return x.xxx_hidden_AutoUpgrade
	}
	return nil
}

func (x *OptionsConfiguration) GetUsageReporting() *OptionsConfiguration_UsageReporting {
	if x != nil {
		return x.xxx_hidden_UsageReporting
	}
	return nil
}

func (x *OptionsConfiguration) GetAudit() *OptionsConfiguration_Audit {
	if x != nil {
		return x.xxx_hidden_Audit
	}
	return nil
}

func (x *OptionsConfiguration) SetGeneral(v *OptionsConfiguration_General) {
	x.xxx_hidden_General = v
}

func (x *OptionsConfiguration) SetNetwork(v *OptionsConfiguration_Network) {
	x.xxx_hidden_Network = v
}

func (x *OptionsConfiguration) SetAutoUpgrade(v *OptionsConfiguration_AutoUpgrade) {
	x.xxx_hidden_AutoUpgrade = v
}

func (x *OptionsConfiguration) SetUsageReporting(v *OptionsConfiguration_UsageReporting) {
	x.xxx_hidden_UsageReporting = v
}

func (x *OptionsConfiguration) SetAudit(v *OptionsConfiguration_Audit) {
	x.xxx_hidden_Audit = v
}

func (x *OptionsConfiguration) HasGeneral() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_General != nil
}

func (x *OptionsConfiguration) HasNetwork() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Network != nil
}

func (x *OptionsConfiguration) HasAutoUpgrade() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AutoUpgrade != nil
}

func (x *OptionsConfiguration) HasUsageReporting() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UsageReporting != nil
}

func (x *OptionsConfiguration) HasAudit() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Audit != nil
}

func (x *OptionsConfiguration) ClearGeneral() {
	x.xxx_hidden_General = nil
}

func (x *OptionsConfiguration) ClearNetwork() {
	x.xxx_hidden_Network = nil
}

func (x *OptionsConfiguration) ClearAutoUpgrade() {
	x.xxx_hidden_AutoUpgrade = nil
}

func (x *OptionsConfiguration) ClearUsageReporting() {
	x.xxx_hidden_UsageReporting = nil
}

func (x *OptionsConfiguration) ClearAudit() {
	x.xxx_hidden_Audit = nil
}

type OptionsConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	General        *OptionsConfiguration_General
	Network        *OptionsConfiguration_Network
	AutoUpgrade    *OptionsConfiguration_AutoUpgrade
	UsageReporting *OptionsConfiguration_UsageReporting
	Audit          *OptionsConfiguration_Audit
}

func (b0 OptionsConfiguration_builder) Build() *OptionsConfiguration {
	m0 := &OptionsConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_General = b.General
	x.xxx_hidden_Network = b.Network
	x.xxx_hidden_AutoUpgrade = b.AutoUpgrade
	x.xxx_hidden_UsageReporting = b.UsageReporting
	x.xxx_hidden_Audit = b.Audit
	return m0
}

type RateLimits struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MaxSendKbps int32                  `protobuf:"varint,1,opt,name=max_send_kbps,json=maxSendKbps"`
	xxx_hidden_MaxRecvKbps int32                  `protobuf:"varint,2,opt,name=max_recv_kbps,json=maxRecvKbps"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RateLimits) GetMaxSendKbps() int32 {
	if x != nil {
		return x.xxx_hidden_MaxSendKbps
	}
	return 0
}

func (x *RateLimits) GetMaxRecvKbps() int32 {
	if x != nil {
		return x.xxx_hidden_MaxRecvKbps
	}
	return 0
}

func (x *RateLimits) SetMaxSendKbps(v int32) {
	x.xxx_hidden_MaxSendKbps = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RateLimits) SetMaxRecvKbps(v int32) {
	x.xxx_hidden_MaxRecvKbps = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RateLimits) HasMaxSendKbps() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RateLimits) HasMaxRecvKbps() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RateLimits) ClearMaxSendKbps() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MaxSendKbps = 0
}

func (x *RateLimits) ClearMaxRecvKbps() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MaxRecvKbps = 0
}

type RateLimits_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MaxSendKbps *int32
	MaxRecvKbps *int32
}

func (b0 RateLimits_builder) Build() *RateLimits {
	m0 := &RateLimits{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MaxSendKbps != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_MaxSendKbps = *b.MaxSendKbps
	}
	if b.MaxRecvKbps != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_MaxRecvKbps = *b.MaxRecvKbps
	}
	return m0
}

type URLs struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Urls []string               `protobuf:"bytes,1,rep,name=urls"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *URLs) Reset() {
	*x = URLs{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLs) ProtoMessage() {}

func (x *URLs) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLs) GetUrls() []string {
	if x != nil {
		return x.xxx_hidden_Urls
	}
	return nil
}

func (x *URLs) SetUrls(v []string) {
	x.xxx_hidden_Urls = v
}

type URLs_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Urls []string
}

func (b0 URLs_builder) Build() *URLs {
	m0 := &URLs{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Urls = b.Urls
	return m0
}

type OptionsConfiguration_General struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MyName               *string                `protobuf:"bytes,1,opt,name=my_name,json=myName"`
	xxx_hidden_StartBrowser         bool                   `protobuf:"varint,2,opt,name=start_browser,json=startBrowser,def=1"`
	xxx_hidden_KeepTemporariesS     int32                  `protobuf:"varint,3,opt,name=keep_temporaries_s,json=keepTemporariesS,def=86400"`
	xxx_hidden_CacheIgnoredFiles    bool                   `protobuf:"varint,4,opt,name=cache_ignored_files,json=cacheIgnoredFiles"`
	xxx_hidden_OverwriteRemoteNames bool                   `protobuf:"varint,5,opt,name=overwrite_remote_names,json=overwriteRemoteNames"`
	xxx_hidden_UnackedNotifications []string               `protobuf:"bytes,6,rep,name=unacked_notifications,json=unackedNotifications"`
	xxx_hidden_SetLowPriority       bool                   `protobuf:"varint,7,opt,name=set_low_priority,json=setLowPriority,def=1"`
	xxx_hidden_MaxFolderConcurrency int32                  `protobuf:"varint,8,opt,name=max_folder_concurrency,json=maxFolderConcurrency"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

// Default values for OptionsConfiguration_General fields.
const (
	Default_OptionsConfiguration_General_StartBrowser     = bool(true)
	Default_OptionsConfiguration_General_KeepTemporariesS = int32(86400)
	Default_OptionsConfiguration_General_SetLowPriority   = bool(true)
)

func (x *OptionsConfiguration_General) Reset() {
	*x = OptionsConfiguration_General{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_General) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_General) ProtoMessage() {}

func (x *OptionsConfiguration_General) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_General) GetMyName() string {
	if x != nil {
		if x.xxx_hidden_MyName != nil {
			return *x.xxx_hidden_MyName
		}
		return ""
	}
	return ""
}

func (x *OptionsConfiguration_General) GetStartBrowser() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_StartBrowser
		}
	}
	return Default_OptionsConfiguration_General_StartBrowser
}

func (x *OptionsConfiguration_General) GetKeepTemporariesS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_KeepTemporariesS
		}
	}
	return Default_OptionsConfiguration_General_KeepTemporariesS
}

func (x *OptionsConfiguration_General) GetCacheIgnoredFiles() bool {
	if x != nil {
		return x.xxx_hidden_CacheIgnoredFiles
	}
	return false
}

func (x *OptionsConfiguration_General) GetOverwriteRemoteNames() bool {
	if x != nil {
		return x.xxx_hidden_OverwriteRemoteNames
	}
	return false
}

func (x *OptionsConfiguration_General) GetUnackedNotifications() []string {
	if x != nil {
		return x.xxx_hidden_UnackedNotifications
	}
	return nil
}

func (x *OptionsConfiguration_General) GetSetLowPriority() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_SetLowPriority
		}
	}
	return Default_OptionsConfiguration_General_SetLowPriority
}

func (x *OptionsConfiguration_General) GetMaxFolderConcurrency() int32 {
	if x != nil {
		return x.xxx_hidden_MaxFolderConcurrency
	}
	return 0
}

func (x *OptionsConfiguration_General) SetMyName(v string) {
	x.xxx_hidden_MyName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *OptionsConfiguration_General) SetStartBrowser(v bool) {
	x.xxx_hidden_StartBrowser = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *OptionsConfiguration_General) SetKeepTemporariesS(v int32) {
	x.xxx_hidden_KeepTemporariesS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *OptionsConfiguration_General) SetCacheIgnoredFiles(v bool) {
	x.xxx_hidden_CacheIgnoredFiles = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *OptionsConfiguration_General) SetOverwriteRemoteNames(v bool) {
	x.xxx_hidden_OverwriteRemoteNames = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *OptionsConfiguration_General) SetUnackedNotifications(v []string) {
	x.xxx_hidden_UnackedNotifications = v
}

func (x *OptionsConfiguration_General) SetSetLowPriority(v bool) {
	x.xxx_hidden_SetLowPriority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *OptionsConfiguration_General) SetMaxFolderConcurrency(v int32) {
	x.xxx_hidden_MaxFolderConcurrency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *OptionsConfiguration_General) HasMyName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_General) HasStartBrowser() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_General) HasKeepTemporariesS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_General) HasCacheIgnoredFiles() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_General) HasOverwriteRemoteNames() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_General) HasSetLowPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *OptionsConfiguration_General) HasMaxFolderConcurrency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *OptionsConfiguration_General) ClearMyName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MyName = nil
}

func (x *OptionsConfiguration_General) ClearStartBrowser() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_General) ClearKeepTemporariesS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_General) ClearCacheIgnoredFiles() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_CacheIgnoredFiles = false
}

func (x *OptionsConfiguration_General) ClearOverwriteRemoteNames() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_OverwriteRemoteNames = false
}

func (x *OptionsConfiguration_General) ClearSetLowPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
}

func (x *OptionsConfiguration_General) ClearMaxFolderConcurrency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_MaxFolderConcurrency = 0
}

type OptionsConfiguration_General_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MyName               *string
	StartBrowser         *bool
	KeepTemporariesS     *int32
	CacheIgnoredFiles    *bool
	OverwriteRemoteNames *bool
	UnackedNotifications []string
	SetLowPriority       *bool
	MaxFolderConcurrency *int32
}

func (b0 OptionsConfiguration_General_builder) Build() *OptionsConfiguration_General {
	m0 := &OptionsConfiguration_General{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MyName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_MyName = b.MyName
	}
	if b.StartBrowser != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_StartBrowser = *b.StartBrowser
	}
	if b.KeepTemporariesS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_KeepTemporariesS = *b.KeepTemporariesS
	}
	if b.CacheIgnoredFiles != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_CacheIgnoredFiles = *b.CacheIgnoredFiles
	}
	if b.OverwriteRemoteNames != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_OverwriteRemoteNames = *b.OverwriteRemoteNames
	}
	x.xxx_hidden_UnackedNotifications = b.UnackedNotifications
	if b.SetLowPriority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_SetLowPriority = *b.SetLowPriority
	}
	if b.MaxFolderConcurrency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_MaxFolderConcurrency = *b.MaxFolderConcurrency
	}
	return m0
}

type OptionsConfiguration_Network struct {
	state                                      protoimpl.MessageState                             `protogen:"opaque.v1"`
	xxx_hidden_Listen                          *URLs                                              `protobuf:"bytes,1,opt,name=listen"`
	xxx_hidden_RateLimitLanConnections         bool                                               `protobuf:"varint,2,opt,name=rate_limit_lan_connections,json=rateLimitLanConnections"`
	xxx_hidden_ReconnectIntervalS              int32                                              `protobuf:"varint,3,opt,name=reconnect_interval_s,json=reconnectIntervalS,def=60"`
	xxx_hidden_AlwaysLocalNetworks             []string                                           `protobuf:"bytes,4,rep,name=always_local_networks,json=alwaysLocalNetworks"`
	xxx_hidden_TrafficClass                    int32                                              `protobuf:"varint,5,opt,name=traffic_class,json=trafficClass"`
	xxx_hidden_MaxConcurrentIncomingRequestKib int32                                              `protobuf:"varint,6,opt,name=max_concurrent_incoming_request_kib,json=maxConcurrentIncomingRequestKib,def=262144"`
	xxx_hidden_ProgressUpdateIntervalS         int32                                              `protobuf:"varint,7,opt,name=progress_update_interval_s,json=progressUpdateIntervalS,def=5"`
	xxx_hidden_TempIndexMinBlocks              int32                                              `protobuf:"varint,8,opt,name=temp_index_min_blocks,json=tempIndexMinBlocks,def=10"`
	xxx_hidden_RateLimits                      *RateLimits                                        `protobuf:"bytes,9,opt,name=rate_limits,json=rateLimits"`
	xxx_hidden_ConnectionLimits                *OptionsConfiguration_Network_ConnectionLimits     `protobuf:"bytes,10,opt,name=connection_limits,json=connectionLimits"`
	xxx_hidden_ConnectionPriorities            *OptionsConfiguration_Network_ConnectionPriorities `protobuf:"bytes,11,opt,name=connection_priorities,json=connectionPriorities"`
	xxx_hidden_Nat                             *OptionsConfiguration_Network_NAT                  `protobuf:"bytes,12,opt,name=nat"`
	xxx_hidden_Discovery                       *OptionsConfiguration_Network_Discovery            `protobuf:"bytes,13,opt,name=discovery"`
	xxx_hidden_Relays                          *OptionsConfiguration_Network_Relays               `protobuf:"bytes,14,opt,name=relays"`
	XXX_raceDetectHookData                     protoimpl.RaceDetectHookData
	XXX_presence                               [1]uint32
	unknownFields                              protoimpl.UnknownFields
	sizeCache                                  protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network fields.
const (
	Default_OptionsConfiguration_Network_ReconnectIntervalS              = int32(60)
	Default_OptionsConfiguration_Network_MaxConcurrentIncomingRequestKib = int32(262144)
	Default_OptionsConfiguration_Network_ProgressUpdateIntervalS         = int32(5)
	Default_OptionsConfiguration_Network_TempIndexMinBlocks              = int32(10)
)

func (x *OptionsConfiguration_Network) Reset() {
	*x = OptionsConfiguration_Network{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network) ProtoMessage() {}

func (x *OptionsConfiguration_Network) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network) GetListen() *URLs {
	if x != nil {
		return x.xxx_hidden_Listen
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetRateLimitLanConnections() bool {
	if x != nil {
		return x.xxx_hidden_RateLimitLanConnections
	}
	return false
}

func (x *OptionsConfiguration_Network) GetReconnectIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_ReconnectIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_ReconnectIntervalS
}

func (x *OptionsConfiguration_Network) GetAlwaysLocalNetworks() []string {
	if x != nil {
		return x.xxx_hidden_AlwaysLocalNetworks
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetTrafficClass() int32 {
	if x != nil {
		return x.xxx_hidden_TrafficClass
	}
	return 0
}

func (x *OptionsConfiguration_Network) GetMaxConcurrentIncomingRequestKib() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_MaxConcurrentIncomingRequestKib
		}
	}
	return Default_OptionsConfiguration_Network_MaxConcurrentIncomingRequestKib
}

func (x *OptionsConfiguration_Network) GetProgressUpdateIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_ProgressUpdateIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_ProgressUpdateIntervalS
}

func (x *OptionsConfiguration_Network) GetTempIndexMinBlocks() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 7) {
			return x.xxx_hidden_TempIndexMinBlocks
		}
	}
	return Default_OptionsConfiguration_Network_TempIndexMinBlocks
}

func (x *OptionsConfiguration_Network) GetRateLimits() *RateLimits {
	if x != nil {
		return x.xxx_hidden_RateLimits
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetConnectionLimits() *OptionsConfiguration_Network_ConnectionLimits {
	if x != nil {
		return x.xxx_hidden_ConnectionLimits
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetConnectionPriorities() *OptionsConfiguration_Network_ConnectionPriorities {
	if x != nil {
		return x.xxx_hidden_ConnectionPriorities
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetNat() *OptionsConfiguration_Network_NAT {
	if x != nil {
		return x.xxx_hidden_Nat
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetDiscovery() *OptionsConfiguration_Network_Discovery {
	if x != nil {
		return x.xxx_hidden_Discovery
	}
	return nil
}

func (x *OptionsConfiguration_Network) GetRelays() *OptionsConfiguration_Network_Relays {
	if x != nil {
		return x.xxx_hidden_Relays
	}
	return nil
}

func (x *OptionsConfiguration_Network) SetListen(v *URLs) {
	x.xxx_hidden_Listen = v
}

func (x *OptionsConfiguration_Network) SetRateLimitLanConnections(v bool) {
	x.xxx_hidden_RateLimitLanConnections = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 14)
}

func (x *OptionsConfiguration_Network) SetReconnectIntervalS(v int32) {
	x.xxx_hidden_ReconnectIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 14)
}

func (x *OptionsConfiguration_Network) SetAlwaysLocalNetworks(v []string) {
	x.xxx_hidden_AlwaysLocalNetworks = v
}

func (x *OptionsConfiguration_Network) SetTrafficClass(v int32) {
	x.xxx_hidden_TrafficClass = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 14)
}

func (x *OptionsConfiguration_Network) SetMaxConcurrentIncomingRequestKib(v int32) {
	x.xxx_hidden_MaxConcurrentIncomingRequestKib = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 14)
}

func (x *OptionsConfiguration_Network) SetProgressUpdateIntervalS(v int32) {
	x.xxx_hidden_ProgressUpdateIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 14)
}

func (x *OptionsConfiguration_Network) SetTempIndexMinBlocks(v int32) {
	x.xxx_hidden_TempIndexMinBlocks = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 14)
}

func (x *OptionsConfiguration_Network) SetRateLimits(v *RateLimits) {
	x.xxx_hidden_RateLimits = v
}

func (x *OptionsConfiguration_Network) SetConnectionLimits(v *OptionsConfiguration_Network_ConnectionLimits) {
	x.xxx_hidden_ConnectionLimits = v
}

func (x *OptionsConfiguration_Network) SetConnectionPriorities(v *OptionsConfiguration_Network_ConnectionPriorities) {
	x.xxx_hidden_ConnectionPriorities = v
}

func (x *OptionsConfiguration_Network) SetNat(v *OptionsConfiguration_Network_NAT) {
	x.xxx_hidden_Nat = v
}

func (x *OptionsConfiguration_Network) SetDiscovery(v *OptionsConfiguration_Network_Discovery) {
	x.xxx_hidden_Discovery = v
}

func (x *OptionsConfiguration_Network) SetRelays(v *OptionsConfiguration_Network_Relays) {
	x.xxx_hidden_Relays = v
}

func (x *OptionsConfiguration_Network) HasListen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Listen != nil
}

func (x *OptionsConfiguration_Network) HasRateLimitLanConnections() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network) HasReconnectIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network) HasTrafficClass() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_Network) HasMaxConcurrentIncomingRequestKib() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *OptionsConfiguration_Network) HasProgressUpdateIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *OptionsConfiguration_Network) HasTempIndexMinBlocks() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *OptionsConfiguration_Network) HasRateLimits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RateLimits != nil
}

func (x *OptionsConfiguration_Network) HasConnectionLimits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ConnectionLimits != nil
}

func (x *OptionsConfiguration_Network) HasConnectionPriorities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ConnectionPriorities != nil
}

func (x *OptionsConfiguration_Network) HasNat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nat != nil
}

func (x *OptionsConfiguration_Network) HasDiscovery() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Discovery != nil
}

func (x *OptionsConfiguration_Network) HasRelays() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Relays != nil
}

func (x *OptionsConfiguration_Network) ClearListen() {
	x.xxx_hidden_Listen = nil
}

func (x *OptionsConfiguration_Network) ClearRateLimitLanConnections() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RateLimitLanConnections = false
}

func (x *OptionsConfiguration_Network) ClearReconnectIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network) ClearTrafficClass() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TrafficClass = 0
}

func (x *OptionsConfiguration_Network) ClearMaxConcurrentIncomingRequestKib() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

func (x *OptionsConfiguration_Network) ClearProgressUpdateIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
}

func (x *OptionsConfiguration_Network) ClearTempIndexMinBlocks() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
}

func (x *OptionsConfiguration_Network) ClearRateLimits() {
	x.xxx_hidden_RateLimits = nil
}

func (x *OptionsConfiguration_Network) ClearConnectionLimits() {
	x.xxx_hidden_ConnectionLimits = nil
}

func (x *OptionsConfiguration_Network) ClearConnectionPriorities() {
	x.xxx_hidden_ConnectionPriorities = nil
}

func (x *OptionsConfiguration_Network) ClearNat() {
	x.xxx_hidden_Nat = nil
}

func (x *OptionsConfiguration_Network) ClearDiscovery() {
	x.xxx_hidden_Discovery = nil
}

func (x *OptionsConfiguration_Network) ClearRelays() {
	x.xxx_hidden_Relays = nil
}

type OptionsConfiguration_Network_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Listen                          *URLs
	RateLimitLanConnections         *bool
	ReconnectIntervalS              *int32
	AlwaysLocalNetworks             []string
	TrafficClass                    *int32
	MaxConcurrentIncomingRequestKib *int32
	ProgressUpdateIntervalS         *int32
	TempIndexMinBlocks              *int32
	RateLimits                      *RateLimits
	ConnectionLimits                *OptionsConfiguration_Network_ConnectionLimits
	ConnectionPriorities            *OptionsConfiguration_Network_ConnectionPriorities
	Nat                             *OptionsConfiguration_Network_NAT
	Discovery                       *OptionsConfiguration_Network_Discovery
	Relays                          *OptionsConfiguration_Network_Relays
}

func (b0 OptionsConfiguration_Network_builder) Build() *OptionsConfiguration_Network {
	m0 := &OptionsConfiguration_Network{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Listen = b.Listen
	if b.RateLimitLanConnections != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 14)
		x.xxx_hidden_RateLimitLanConnections = *b.RateLimitLanConnections
	}
	if b.ReconnectIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 14)
		x.xxx_hidden_ReconnectIntervalS = *b.ReconnectIntervalS
	}
	x.xxx_hidden_AlwaysLocalNetworks = b.AlwaysLocalNetworks
	if b.TrafficClass != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 14)
		x.xxx_hidden_TrafficClass = *b.TrafficClass
	}
	if b.MaxConcurrentIncomingRequestKib != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 14)
		x.xxx_hidden_MaxConcurrentIncomingRequestKib = *b.MaxConcurrentIncomingRequestKib
	}
	if b.ProgressUpdateIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 14)
		x.xxx_hidden_ProgressUpdateIntervalS = *b.ProgressUpdateIntervalS
	}
	if b.TempIndexMinBlocks != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 14)
		x.xxx_hidden_TempIndexMinBlocks = *b.TempIndexMinBlocks
	}
	x.xxx_hidden_RateLimits = b.RateLimits
	x.xxx_hidden_ConnectionLimits = b.ConnectionLimits
	x.xxx_hidden_ConnectionPriorities = b.ConnectionPriorities
	x.xxx_hidden_Nat = b.Nat
	x.xxx_hidden_Discovery = b.Discovery
	x.xxx_hidden_Relays = b.Relays
	return m0
}

type OptionsConfiguration_AutoUpgrade struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_CheckIntervalS    int32                  `protobuf:"varint,2,opt,name=check_interval_s,json=checkIntervalS,def=43200"`
	xxx_hidden_ReleaseCandidates bool                   `protobuf:"varint,3,opt,name=release_candidates,json=releaseCandidates"`
	xxx_hidden_ServerUrl         *string                `protobuf:"bytes,4,opt,name=server_url,json=serverUrl,def=https://upgrades.syncthing.net/meta.json"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

// Default values for OptionsConfiguration_AutoUpgrade fields.
const (
	Default_OptionsConfiguration_AutoUpgrade_Enabled        = bool(true)
	Default_OptionsConfiguration_AutoUpgrade_CheckIntervalS = int32(43200)
	Default_OptionsConfiguration_AutoUpgrade_ServerUrl      = string("https://upgrades.syncthing.net/meta.json")
)

func (x *OptionsConfiguration_AutoUpgrade) Reset() {
	*x = OptionsConfiguration_AutoUpgrade{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_AutoUpgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_AutoUpgrade) ProtoMessage() {}

func (x *OptionsConfiguration_AutoUpgrade) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_AutoUpgrade) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_AutoUpgrade_Enabled
}

func (x *OptionsConfiguration_AutoUpgrade) GetCheckIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_CheckIntervalS
		}
	}
	return Default_OptionsConfiguration_AutoUpgrade_CheckIntervalS
}

func (x *OptionsConfiguration_AutoUpgrade) GetReleaseCandidates() bool {
	if x != nil {
		return x.xxx_hidden_ReleaseCandidates
	}
	return false
}

func (x *OptionsConfiguration_AutoUpgrade) GetServerUrl() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if x.xxx_hidden_ServerUrl != nil {
				return *x.xxx_hidden_ServerUrl
			}
			return Default_OptionsConfiguration_AutoUpgrade_ServerUrl
		}
	}
	return Default_OptionsConfiguration_AutoUpgrade_ServerUrl
}

func (x *OptionsConfiguration_AutoUpgrade) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OptionsConfiguration_AutoUpgrade) SetCheckIntervalS(v int32) {
	x.xxx_hidden_CheckIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OptionsConfiguration_AutoUpgrade) SetReleaseCandidates(v bool) {
	x.xxx_hidden_ReleaseCandidates = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *OptionsConfiguration_AutoUpgrade) SetServerUrl(v string) {
	x.xxx_hidden_ServerUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *OptionsConfiguration_AutoUpgrade) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_AutoUpgrade) HasCheckIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_AutoUpgrade) HasReleaseCandidates() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_AutoUpgrade) HasServerUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_AutoUpgrade) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_AutoUpgrade) ClearCheckIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_AutoUpgrade) ClearReleaseCandidates() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ReleaseCandidates = false
}

func (x *OptionsConfiguration_AutoUpgrade) ClearServerUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

type OptionsConfiguration_AutoUpgrade_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled           *bool
	CheckIntervalS    *int32
	ReleaseCandidates *bool
	ServerUrl         *string
}

func (b0 OptionsConfiguration_AutoUpgrade_builder) Build() *OptionsConfiguration_AutoUpgrade {
	m0 := &OptionsConfiguration_AutoUpgrade{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.CheckIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_CheckIntervalS = *b.CheckIntervalS
	}
	if b.ReleaseCandidates != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ReleaseCandidates = *b.ReleaseCandidates
	}
	if b.ServerUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ServerUrl = b.ServerUrl
	}
	return m0
}

type OptionsConfiguration_UsageReporting struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_UniqueId      *string                `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId"`
	xxx_hidden_Url           *string                `protobuf:"bytes,3,opt,name=url,def=https://data.syncthing.net/newdata"`
	xxx_hidden_InitialDelayS int32                  `protobuf:"varint,4,opt,name=initial_delay_s,json=initialDelayS,def=1800"`
	xxx_hidden_TlsInsecure   bool                   `protobuf:"varint,5,opt,name=tls_insecure,json=tlsInsecure"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

// Default values for OptionsConfiguration_UsageReporting fields.
const (
	Default_OptionsConfiguration_UsageReporting_Enabled       = bool(true)
	Default_OptionsConfiguration_UsageReporting_Url           = string("https://data.syncthing.net/newdata")
	Default_OptionsConfiguration_UsageReporting_InitialDelayS = int32(1800)
)

func (x *OptionsConfiguration_UsageReporting) Reset() {
	*x = OptionsConfiguration_UsageReporting{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_UsageReporting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_UsageReporting) ProtoMessage() {}

func (x *OptionsConfiguration_UsageReporting) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_UsageReporting) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_UsageReporting_Enabled
}

func (x *OptionsConfiguration_UsageReporting) GetUniqueId() string {
	if x != nil {
		if x.xxx_hidden_UniqueId != nil {
			return *x.xxx_hidden_UniqueId
		}
		return ""
	}
	return ""
}

func (x *OptionsConfiguration_UsageReporting) GetUrl() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if x.xxx_hidden_Url != nil {
				return *x.xxx_hidden_Url
			}
			return Default_OptionsConfiguration_UsageReporting_Url
		}
	}
	return Default_OptionsConfiguration_UsageReporting_Url
}

func (x *OptionsConfiguration_UsageReporting) GetInitialDelayS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_InitialDelayS
		}
	}
	return Default_OptionsConfiguration_UsageReporting_InitialDelayS
}

func (x *OptionsConfiguration_UsageReporting) GetTlsInsecure() bool {
	if x != nil {
		return x.xxx_hidden_TlsInsecure
	}
	return false
}

func (x *OptionsConfiguration_UsageReporting) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *OptionsConfiguration_UsageReporting) SetUniqueId(v string) {
	x.xxx_hidden_UniqueId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *OptionsConfiguration_UsageReporting) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *OptionsConfiguration_UsageReporting) SetInitialDelayS(v int32) {
	x.xxx_hidden_InitialDelayS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *OptionsConfiguration_UsageReporting) SetTlsInsecure(v bool) {
	x.xxx_hidden_TlsInsecure = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *OptionsConfiguration_UsageReporting) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_UsageReporting) HasUniqueId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_UsageReporting) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_UsageReporting) HasInitialDelayS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_UsageReporting) HasTlsInsecure() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_UsageReporting) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_UsageReporting) ClearUniqueId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UniqueId = nil
}

func (x *OptionsConfiguration_UsageReporting) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_UsageReporting) ClearInitialDelayS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_UsageReporting) ClearTlsInsecure() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TlsInsecure = false
}

type OptionsConfiguration_UsageReporting_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled       *bool
	UniqueId      *string
	Url           *string
	InitialDelayS *int32
	TlsInsecure   *bool
}

func (b0 OptionsConfiguration_UsageReporting_builder) Build() *OptionsConfiguration_UsageReporting {
	m0 := &OptionsConfiguration_UsageReporting{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.UniqueId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_UniqueId = b.UniqueId
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Url = b.Url
	}
	if b.InitialDelayS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_InitialDelayS = *b.InitialDelayS
	}
	if b.TlsInsecure != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_TlsInsecure = *b.TlsInsecure
	}
	return m0
}

type OptionsConfiguration_Audit struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_File        *string                `protobuf:"bytes,2,opt,name=file"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OptionsConfiguration_Audit) Reset() {
	*x = OptionsConfiguration_Audit{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Audit) ProtoMessage() {}

func (x *OptionsConfiguration_Audit) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Audit) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *OptionsConfiguration_Audit) GetFile() string {
	if x != nil {
		if x.xxx_hidden_File != nil {
			return *x.xxx_hidden_File
		}
		return ""
	}
	return ""
}

func (x *OptionsConfiguration_Audit) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OptionsConfiguration_Audit) SetFile(v string) {
	x.xxx_hidden_File = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OptionsConfiguration_Audit) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Audit) HasFile() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Audit) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *OptionsConfiguration_Audit) ClearFile() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_File = nil
}

type OptionsConfiguration_Audit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled *bool
	File    *string
}

func (b0 OptionsConfiguration_Audit_builder) Build() *OptionsConfiguration_Audit {
	m0 := &OptionsConfiguration_Audit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.File != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_File = b.File
	}
	return m0
}

type OptionsConfiguration_Network_ConnectionLimits struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enough      int32                  `protobuf:"varint,1,opt,name=enough"`
	xxx_hidden_Max         int32                  `protobuf:"varint,2,opt,name=max"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OptionsConfiguration_Network_ConnectionLimits) Reset() {
	*x = OptionsConfiguration_Network_ConnectionLimits{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_ConnectionLimits) ProtoMessage() {}

func (x *OptionsConfiguration_Network_ConnectionLimits) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) GetEnough() int32 {
	if x != nil {
		return x.xxx_hidden_Enough
	}
	return 0
}

func (x *OptionsConfiguration_Network_ConnectionLimits) GetMax() int32 {
	if x != nil {
		return x.xxx_hidden_Max
	}
	return 0
}

func (x *OptionsConfiguration_Network_ConnectionLimits) SetEnough(v int32) {
	x.xxx_hidden_Enough = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) SetMax(v int32) {
	x.xxx_hidden_Max = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) HasEnough() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) HasMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_ConnectionLimits) ClearEnough() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enough = 0
}

func (x *OptionsConfiguration_Network_ConnectionLimits) ClearMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Max = 0
}

type OptionsConfiguration_Network_ConnectionLimits_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enough *int32
	Max    *int32
}

func (b0 OptionsConfiguration_Network_ConnectionLimits_builder) Build() *OptionsConfiguration_Network_ConnectionLimits {
	m0 := &OptionsConfiguration_Network_ConnectionLimits{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enough != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Enough = *b.Enough
	}
	if b.Max != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Max = *b.Max
	}
	return m0
}

type OptionsConfiguration_Network_ConnectionPriorities struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TcpLan           int32                  `protobuf:"varint,1,opt,name=tcp_lan,json=tcpLan,def=10"`
	xxx_hidden_QuicLan          int32                  `protobuf:"varint,2,opt,name=quic_lan,json=quicLan,def=20"`
	xxx_hidden_TcpWan           int32                  `protobuf:"varint,3,opt,name=tcp_wan,json=tcpWan,def=30"`
	xxx_hidden_QuicWan          int32                  `protobuf:"varint,4,opt,name=quic_wan,json=quicWan,def=40"`
	xxx_hidden_Relays           int32                  `protobuf:"varint,5,opt,name=relays,def=50"`
	xxx_hidden_UpgradeThreshold int32                  `protobuf:"varint,6,opt,name=upgrade_threshold,json=upgradeThreshold"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network_ConnectionPriorities fields.
const (
	Default_OptionsConfiguration_Network_ConnectionPriorities_TcpLan  = int32(10)
	Default_OptionsConfiguration_Network_ConnectionPriorities_QuicLan = int32(20)
	Default_OptionsConfiguration_Network_ConnectionPriorities_TcpWan  = int32(30)
	Default_OptionsConfiguration_Network_ConnectionPriorities_QuicWan = int32(40)
	Default_OptionsConfiguration_Network_ConnectionPriorities_Relays  = int32(50)
)

func (x *OptionsConfiguration_Network_ConnectionPriorities) Reset() {
	*x = OptionsConfiguration_Network_ConnectionPriorities{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_ConnectionPriorities) ProtoMessage() {}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetTcpLan() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_TcpLan
		}
	}
	return Default_OptionsConfiguration_Network_ConnectionPriorities_TcpLan
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetQuicLan() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_QuicLan
		}
	}
	return Default_OptionsConfiguration_Network_ConnectionPriorities_QuicLan
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetTcpWan() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_TcpWan
		}
	}
	return Default_OptionsConfiguration_Network_ConnectionPriorities_TcpWan
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetQuicWan() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_QuicWan
		}
	}
	return Default_OptionsConfiguration_Network_ConnectionPriorities_QuicWan
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetRelays() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Relays
		}
	}
	return Default_OptionsConfiguration_Network_ConnectionPriorities_Relays
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) GetUpgradeThreshold() int32 {
	if x != nil {
		return x.xxx_hidden_UpgradeThreshold
	}
	return 0
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetTcpLan(v int32) {
	x.xxx_hidden_TcpLan = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetQuicLan(v int32) {
	x.xxx_hidden_QuicLan = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetTcpWan(v int32) {
	x.xxx_hidden_TcpWan = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetQuicWan(v int32) {
	x.xxx_hidden_QuicWan = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetRelays(v int32) {
	x.xxx_hidden_Relays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) SetUpgradeThreshold(v int32) {
	x.xxx_hidden_UpgradeThreshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasTcpLan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasQuicLan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasTcpWan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasQuicWan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasRelays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) HasUpgradeThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearTcpLan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearQuicLan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearTcpWan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearQuicWan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearRelays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_Network_ConnectionPriorities) ClearUpgradeThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_UpgradeThreshold = 0
}

type OptionsConfiguration_Network_ConnectionPriorities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TcpLan           *int32
	QuicLan          *int32
	TcpWan           *int32
	QuicWan          *int32
	Relays           *int32
	UpgradeThreshold *int32
}

func (b0 OptionsConfiguration_Network_ConnectionPriorities_builder) Build() *OptionsConfiguration_Network_ConnectionPriorities {
	m0 := &OptionsConfiguration_Network_ConnectionPriorities{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TcpLan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_TcpLan = *b.TcpLan
	}
	if b.QuicLan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_QuicLan = *b.QuicLan
	}
	if b.TcpWan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_TcpWan = *b.TcpWan
	}
	if b.QuicWan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_QuicWan = *b.QuicWan
	}
	if b.Relays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Relays = *b.Relays
	}
	if b.UpgradeThreshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_UpgradeThreshold = *b.UpgradeThreshold
	}
	return m0
}

type OptionsConfiguration_Network_NAT struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_LeaseIntervalS      int32                  `protobuf:"varint,2,opt,name=lease_interval_s,json=leaseIntervalS,def=3600"`
	xxx_hidden_RenewalIntervalS    int32                  `protobuf:"varint,3,opt,name=renewal_interval_s,json=renewalIntervalS,def=1800"`
	xxx_hidden_TimeoutIntervalS    int32                  `protobuf:"varint,4,opt,name=timeout_interval_s,json=timeoutIntervalS,def=10"`
	xxx_hidden_StunKeepaliveStartS int32                  `protobuf:"varint,5,opt,name=stun_keepalive_start_s,json=stunKeepaliveStartS,def=180"`
	xxx_hidden_StunKeepaliveMinS   int32                  `protobuf:"varint,6,opt,name=stun_keepalive_min_s,json=stunKeepaliveMinS,def=20"`
	xxx_hidden_StunServers         *URLs                  `protobuf:"bytes,7,opt,name=stun_servers,json=stunServers"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network_NAT fields.
const (
	Default_OptionsConfiguration_Network_NAT_Enabled             = bool(true)
	Default_OptionsConfiguration_Network_NAT_LeaseIntervalS      = int32(3600)
	Default_OptionsConfiguration_Network_NAT_RenewalIntervalS    = int32(1800)
	Default_OptionsConfiguration_Network_NAT_TimeoutIntervalS    = int32(10)
	Default_OptionsConfiguration_Network_NAT_StunKeepaliveStartS = int32(180)
	Default_OptionsConfiguration_Network_NAT_StunKeepaliveMinS   = int32(20)
)

func (x *OptionsConfiguration_Network_NAT) Reset() {
	*x = OptionsConfiguration_Network_NAT{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_NAT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_NAT) ProtoMessage() {}

func (x *OptionsConfiguration_Network_NAT) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_NAT) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_Network_NAT_Enabled
}

func (x *OptionsConfiguration_Network_NAT) GetLeaseIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_LeaseIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_NAT_LeaseIntervalS
}

func (x *OptionsConfiguration_Network_NAT) GetRenewalIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_RenewalIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_NAT_RenewalIntervalS
}

func (x *OptionsConfiguration_Network_NAT) GetTimeoutIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_TimeoutIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_NAT_TimeoutIntervalS
}

func (x *OptionsConfiguration_Network_NAT) GetStunKeepaliveStartS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_StunKeepaliveStartS
		}
	}
	return Default_OptionsConfiguration_Network_NAT_StunKeepaliveStartS
}

func (x *OptionsConfiguration_Network_NAT) GetStunKeepaliveMinS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_StunKeepaliveMinS
		}
	}
	return Default_OptionsConfiguration_Network_NAT_StunKeepaliveMinS
}

func (x *OptionsConfiguration_Network_NAT) GetStunServers() *URLs {
	if x != nil {
		return x.xxx_hidden_StunServers
	}
	return nil
}

func (x *OptionsConfiguration_Network_NAT) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetLeaseIntervalS(v int32) {
	x.xxx_hidden_LeaseIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetRenewalIntervalS(v int32) {
	x.xxx_hidden_RenewalIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetTimeoutIntervalS(v int32) {
	x.xxx_hidden_TimeoutIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetStunKeepaliveStartS(v int32) {
	x.xxx_hidden_StunKeepaliveStartS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetStunKeepaliveMinS(v int32) {
	x.xxx_hidden_StunKeepaliveMinS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *OptionsConfiguration_Network_NAT) SetStunServers(v *URLs) {
	x.xxx_hidden_StunServers = v
}

func (x *OptionsConfiguration_Network_NAT) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_NAT) HasLeaseIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_NAT) HasRenewalIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network_NAT) HasTimeoutIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_Network_NAT) HasStunKeepaliveStartS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_Network_NAT) HasStunKeepaliveMinS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *OptionsConfiguration_Network_NAT) HasStunServers() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StunServers != nil
}

func (x *OptionsConfiguration_Network_NAT) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_NAT) ClearLeaseIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_NAT) ClearRenewalIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network_NAT) ClearTimeoutIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *OptionsConfiguration_Network_NAT) ClearStunKeepaliveStartS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

func (x *OptionsConfiguration_Network_NAT) ClearStunKeepaliveMinS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

func (x *OptionsConfiguration_Network_NAT) ClearStunServers() {
	x.xxx_hidden_StunServers = nil
}

type OptionsConfiguration_Network_NAT_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled             *bool
	LeaseIntervalS      *int32
	RenewalIntervalS    *int32
	TimeoutIntervalS    *int32
	StunKeepaliveStartS *int32
	StunKeepaliveMinS   *int32
	StunServers         *URLs
}

func (b0 OptionsConfiguration_Network_NAT_builder) Build() *OptionsConfiguration_Network_NAT {
	m0 := &OptionsConfiguration_Network_NAT{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.LeaseIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_LeaseIntervalS = *b.LeaseIntervalS
	}
	if b.RenewalIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_RenewalIntervalS = *b.RenewalIntervalS
	}
	if b.TimeoutIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_TimeoutIntervalS = *b.TimeoutIntervalS
	}
	if b.StunKeepaliveStartS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_StunKeepaliveStartS = *b.StunKeepaliveStartS
	}
	if b.StunKeepaliveMinS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_StunKeepaliveMinS = *b.StunKeepaliveMinS
	}
	x.xxx_hidden_StunServers = b.StunServers
	return m0
}

type OptionsConfiguration_Network_Discovery struct {
	state                           protoimpl.MessageState                         `protogen:"opaque.v1"`
	xxx_hidden_AnnounceLanAddresses bool                                           `protobuf:"varint,1,opt,name=announce_lan_addresses,json=announceLanAddresses"`
	xxx_hidden_Local                *OptionsConfiguration_Network_Discovery_Local  `protobuf:"bytes,2,opt,name=local"`
	xxx_hidden_Global               *OptionsConfiguration_Network_Discovery_Global `protobuf:"bytes,3,opt,name=global"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *OptionsConfiguration_Network_Discovery) Reset() {
	*x = OptionsConfiguration_Network_Discovery{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_Discovery) ProtoMessage() {}

func (x *OptionsConfiguration_Network_Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_Discovery) GetAnnounceLanAddresses() bool {
	if x != nil {
		return x.xxx_hidden_AnnounceLanAddresses
	}
	return false
}

func (x *OptionsConfiguration_Network_Discovery) GetLocal() *OptionsConfiguration_Network_Discovery_Local {
	if x != nil {
		return x.xxx_hidden_Local
	}
	return nil
}

func (x *OptionsConfiguration_Network_Discovery) GetGlobal() *OptionsConfiguration_Network_Discovery_Global {
	if x != nil {
		return x.xxx_hidden_Global
	}
	return nil
}

func (x *OptionsConfiguration_Network_Discovery) SetAnnounceLanAddresses(v bool) {
	x.xxx_hidden_AnnounceLanAddresses = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *OptionsConfiguration_Network_Discovery) SetLocal(v *OptionsConfiguration_Network_Discovery_Local) {
	x.xxx_hidden_Local = v
}

func (x *OptionsConfiguration_Network_Discovery) SetGlobal(v *OptionsConfiguration_Network_Discovery_Global) {
	x.xxx_hidden_Global = v
}

func (x *OptionsConfiguration_Network_Discovery) HasAnnounceLanAddresses() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Discovery) HasLocal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Local != nil
}

func (x *OptionsConfiguration_Network_Discovery) HasGlobal() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Global != nil
}

func (x *OptionsConfiguration_Network_Discovery) ClearAnnounceLanAddresses() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AnnounceLanAddresses = false
}

func (x *OptionsConfiguration_Network_Discovery) ClearLocal() {
	x.xxx_hidden_Local = nil
}

func (x *OptionsConfiguration_Network_Discovery) ClearGlobal() {
	x.xxx_hidden_Global = nil
}

type OptionsConfiguration_Network_Discovery_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AnnounceLanAddresses *bool
	Local                *OptionsConfiguration_Network_Discovery_Local
	Global               *OptionsConfiguration_Network_Discovery_Global
}

func (b0 OptionsConfiguration_Network_Discovery_builder) Build() *OptionsConfiguration_Network_Discovery {
	m0 := &OptionsConfiguration_Network_Discovery{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AnnounceLanAddresses != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_AnnounceLanAddresses = *b.AnnounceLanAddresses
	}
	x.xxx_hidden_Local = b.Local
	x.xxx_hidden_Global = b.Global
	return m0
}

type OptionsConfiguration_Network_Relays struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled            bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_ReconnectIntervalS int32                  `protobuf:"varint,2,opt,name=reconnect_interval_s,json=reconnectIntervalS,def=600"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network_Relays fields.
const (
	Default_OptionsConfiguration_Network_Relays_Enabled            = bool(true)
	Default_OptionsConfiguration_Network_Relays_ReconnectIntervalS = int32(600)
)

func (x *OptionsConfiguration_Network_Relays) Reset() {
	*x = OptionsConfiguration_Network_Relays{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_Relays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_Relays) ProtoMessage() {}

func (x *OptionsConfiguration_Network_Relays) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_Relays) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_Network_Relays_Enabled
}

func (x *OptionsConfiguration_Network_Relays) GetReconnectIntervalS() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_ReconnectIntervalS
		}
	}
	return Default_OptionsConfiguration_Network_Relays_ReconnectIntervalS
}

func (x *OptionsConfiguration_Network_Relays) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OptionsConfiguration_Network_Relays) SetReconnectIntervalS(v int32) {
	x.xxx_hidden_ReconnectIntervalS = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *OptionsConfiguration_Network_Relays) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Relays) HasReconnectIntervalS() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_Relays) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Relays) ClearReconnectIntervalS() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

type OptionsConfiguration_Network_Relays_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled            *bool
	ReconnectIntervalS *int32
}

func (b0 OptionsConfiguration_Network_Relays_builder) Build() *OptionsConfiguration_Network_Relays {
	m0 := &OptionsConfiguration_Network_Relays{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.ReconnectIntervalS != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ReconnectIntervalS = *b.ReconnectIntervalS
	}
	return m0
}

type OptionsConfiguration_Network_Discovery_Local struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled              bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_Ipv4Port             int32                  `protobuf:"varint,2,opt,name=ipv4_port,json=ipv4Port,def=21027"`
	xxx_hidden_Ipv6MulticastAddress *string                `protobuf:"bytes,3,opt,name=ipv6_multicast_address,json=ipv6MulticastAddress,def=[ff12::8384]:21027"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network_Discovery_Local fields.
const (
	Default_OptionsConfiguration_Network_Discovery_Local_Enabled              = bool(true)
	Default_OptionsConfiguration_Network_Discovery_Local_Ipv4Port             = int32(21027)
	Default_OptionsConfiguration_Network_Discovery_Local_Ipv6MulticastAddress = string("[ff12::8384]:21027")
)

func (x *OptionsConfiguration_Network_Discovery_Local) Reset() {
	*x = OptionsConfiguration_Network_Discovery_Local{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_Discovery_Local) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_Discovery_Local) ProtoMessage() {}

func (x *OptionsConfiguration_Network_Discovery_Local) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_Discovery_Local) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_Network_Discovery_Local_Enabled
}

func (x *OptionsConfiguration_Network_Discovery_Local) GetIpv4Port() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Ipv4Port
		}
	}
	return Default_OptionsConfiguration_Network_Discovery_Local_Ipv4Port
}

func (x *OptionsConfiguration_Network_Discovery_Local) GetIpv6MulticastAddress() string {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if x.xxx_hidden_Ipv6MulticastAddress != nil {
				return *x.xxx_hidden_Ipv6MulticastAddress
			}
			return Default_OptionsConfiguration_Network_Discovery_Local_Ipv6MulticastAddress
		}
	}
	return Default_OptionsConfiguration_Network_Discovery_Local_Ipv6MulticastAddress
}

func (x *OptionsConfiguration_Network_Discovery_Local) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *OptionsConfiguration_Network_Discovery_Local) SetIpv4Port(v int32) {
	x.xxx_hidden_Ipv4Port = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *OptionsConfiguration_Network_Discovery_Local) SetIpv6MulticastAddress(v string) {
	x.xxx_hidden_Ipv6MulticastAddress = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *OptionsConfiguration_Network_Discovery_Local) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Discovery_Local) HasIpv4Port() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_Discovery_Local) HasIpv6MulticastAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OptionsConfiguration_Network_Discovery_Local) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Discovery_Local) ClearIpv4Port() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

func (x *OptionsConfiguration_Network_Discovery_Local) ClearIpv6MulticastAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

type OptionsConfiguration_Network_Discovery_Local_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled              *bool
	Ipv4Port             *int32
	Ipv6MulticastAddress *string
}

func (b0 OptionsConfiguration_Network_Discovery_Local_builder) Build() *OptionsConfiguration_Network_Discovery_Local {
	m0 := &OptionsConfiguration_Network_Discovery_Local{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.Ipv4Port != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Ipv4Port = *b.Ipv4Port
	}
	if b.Ipv6MulticastAddress != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Ipv6MulticastAddress = b.Ipv6MulticastAddress
	}
	return m0
}

type OptionsConfiguration_Network_Discovery_Global struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,1,opt,name=enabled,def=1"`
	xxx_hidden_Servers     *URLs                  `protobuf:"bytes,2,opt,name=servers"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for OptionsConfiguration_Network_Discovery_Global fields.
const (
	Default_OptionsConfiguration_Network_Discovery_Global_Enabled = bool(true)
)

func (x *OptionsConfiguration_Network_Discovery_Global) Reset() {
	*x = OptionsConfiguration_Network_Discovery_Global{}
	mi := &file_config_v2_options_configuration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsConfiguration_Network_Discovery_Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsConfiguration_Network_Discovery_Global) ProtoMessage() {}

func (x *OptionsConfiguration_Network_Discovery_Global) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_options_configuration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OptionsConfiguration_Network_Discovery_Global) GetEnabled() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Enabled
		}
	}
	return Default_OptionsConfiguration_Network_Discovery_Global_Enabled
}

func (x *OptionsConfiguration_Network_Discovery_Global) GetServers() *URLs {
	if x != nil {
		return x.xxx_hidden_Servers
	}
	return nil
}

func (x *OptionsConfiguration_Network_Discovery_Global) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *OptionsConfiguration_Network_Discovery_Global) SetServers(v *URLs) {
	x.xxx_hidden_Servers = v
}

func (x *OptionsConfiguration_Network_Discovery_Global) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Discovery_Global) HasServers() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Servers != nil
}

func (x *OptionsConfiguration_Network_Discovery_Global) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *OptionsConfiguration_Network_Discovery_Global) ClearServers() {
	x.xxx_hidden_Servers = nil
}

type OptionsConfiguration_Network_Discovery_Global_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Enabled *bool
	Servers *URLs
}

func (b0 OptionsConfiguration_Network_Discovery_Global_builder) Build() *OptionsConfiguration_Network_Discovery_Global {
	m0 := &OptionsConfiguration_Network_Discovery_Global{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_Servers = b.Servers
	return m0
}

var File_config_v2_options_configuration_proto protoreflect.FileDescriptor

const file_config_v2_options_configuration_proto_rawDesc = "" +
	"\n" +
	"%config/v2/options_configuration.proto\x12\x13syncthing.config.v2\x1a!google/protobuf/go_features.proto\"\xf3\x1b\n" +
	"\x14OptionsConfiguration\x12K\n" +
	"\ageneral\x18\x01 \x01(\v21.syncthing.config.v2.OptionsConfiguration.GeneralR\ageneral\x12K\n" +
	"\anetwork\x18\x02 \x01(\v21.syncthing.config.v2.OptionsConfiguration.NetworkR\anetwork\x12X\n" +
	"\fauto_upgrade\x18\x03 \x01(\v25.syncthing.config.v2.OptionsConfiguration.AutoUpgradeR\vautoUpgrade\x12a\n" +
	"\x0fusage_reporting\x18\x04 \x01(\v28.syncthing.config.v2.OptionsConfiguration.UsageReportingR\x0eusageReporting\x12E\n" +
	"\x05audit\x18\x05 \x01(\v2/.syncthing.config.v2.OptionsConfiguration.AuditR\x05audit\x1a\x83\x03\n" +
	"\aGeneral\x12\x17\n" +
	"\amy_name\x18\x01 \x01(\tR\x06myName\x12)\n" +
	"\rstart_browser\x18\x02 \x01(\b:\x04trueR\fstartBrowser\x123\n" +
	"\x12keep_temporaries_s\x18\x03 \x01(\x05:\x0586400R\x10keepTemporariesS\x12.\n" +
	"\x13cache_ignored_files\x18\x04 \x01(\bR\x11cacheIgnoredFiles\x124\n" +
	"\x16overwrite_remote_names\x18\x05 \x01(\bR\x14overwriteRemoteNames\x123\n" +
	"\x15unacked_notifications\x18\x06 \x03(\tR\x14unackedNotifications\x12.\n" +
	"\x10set_low_priority\x18\a \x01(\b:\x04trueR\x0esetLowPriority\x124\n" +
	"\x16max_folder_concurrency\x18\b \x01(\x05R\x14maxFolderConcurrency\x1a\xcf\x11\n" +
	"\aNetwork\x121\n" +
	"\x06listen\x18\x01 \x01(\v2\x19.syncthing.config.v2.URLsR\x06listen\x12;\n" +
	"\x1arate_limit_lan_connections\x18\x02 \x01(\bR\x17rateLimitLanConnections\x124\n" +
	"\x14reconnect_interval_s\x18\x03 \x01(\x05:\x0260R\x12reconnectIntervalS\x122\n" +
	"\x15always_local_networks\x18\x04 \x03(\tR\x13alwaysLocalNetworks\x12#\n" +
	"\rtraffic_class\x18\x05 \x01(\x05R\ftrafficClass\x12T\n" +
	"#max_concurrent_incoming_request_kib\x18\x06 \x01(\x05:\x06262144R\x1fmaxConcurrentIncomingRequestKib\x12>\n" +
	"\x1aprogress_update_interval_s\x18\a \x01(\x05:\x015R\x17progressUpdateIntervalS\x125\n" +
	"\x15temp_index_min_blocks\x18\b \x01(\x05:\x0210R\x12tempIndexMinBlocks\x12@\n" +
	"\vrate_limits\x18\t \x01(\v2\x1f.syncthing.config.v2.RateLimitsR\n" +
	"rateLimits\x12o\n" +
	"\x11connection_limits\x18\n" +
	" \x01(\v2B.syncthing.config.v2.OptionsConfiguration.Network.ConnectionLimitsR\x10connectionLimits\x12{\n" +
	"\x15connection_priorities\x18\v \x01(\v2F.syncthing.config.v2.OptionsConfiguration.Network.ConnectionPrioritiesR\x14connectionPriorities\x12G\n" +
	"\x03nat\x18\f \x01(\v25.syncthing.config.v2.OptionsConfiguration.Network.NATR\x03nat\x12Y\n" +
	"\tdiscovery\x18\r \x01(\v2;.syncthing.config.v2.OptionsConfiguration.Network.DiscoveryR\tdiscovery\x12P\n" +
	"\x06relays\x18\x0e \x01(\v28.syncthing.config.v2.OptionsConfiguration.Network.RelaysR\x06relays\x1a<\n" +
	"\x10ConnectionLimits\x12\x16\n" +
	"\x06enough\x18\x01 \x01(\x05R\x06enough\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x1a\xd7\x01\n" +
	"\x14ConnectionPriorities\x12\x1b\n" +
	"\atcp_lan\x18\x01 \x01(\x05:\x0210R\x06tcpLan\x12\x1d\n" +
	"\bquic_lan\x18\x02 \x01(\x05:\x0220R\aquicLan\x12\x1b\n" +
	"\atcp_wan\x18\x03 \x01(\x05:\x0230R\x06tcpWan\x12\x1d\n" +
	"\bquic_wan\x18\x04 \x01(\x05:\x0240R\aquicWan\x12\x1a\n" +
	"\x06relays\x18\x05 \x01(\x05:\x0250R\x06relays\x12+\n" +
	"\x11upgrade_threshold\x18\x06 \x01(\x05R\x10upgradeThreshold\x1a\xe8\x02\n" +
	"\x03NAT\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x12.\n" +
	"\x10lease_interval_s\x18\x02 \x01(\x05:\x043600R\x0eleaseIntervalS\x122\n" +
	"\x12renewal_interval_s\x18\x03 \x01(\x05:\x041800R\x10renewalIntervalS\x120\n" +
	"\x12timeout_interval_s\x18\x04 \x01(\x05:\x0210R\x10timeoutIntervalS\x128\n" +
	"\x16stun_keepalive_start_s\x18\x05 \x01(\x05:\x03180R\x13stunKeepaliveStartS\x123\n" +
	"\x14stun_keepalive_min_s\x18\x06 \x01(\x05:\x0220R\x11stunKeepaliveMinS\x12<\n" +
	"\fstun_servers\x18\a \x01(\v2\x19.syncthing.config.v2.URLsR\vstunServers\x1a\xed\x03\n" +
	"\tDiscovery\x124\n" +
	"\x16announce_lan_addresses\x18\x01 \x01(\bR\x14announceLanAddresses\x12W\n" +
	"\x05local\x18\x02 \x01(\v2A.syncthing.config.v2.OptionsConfiguration.Network.Discovery.LocalR\x05local\x12Z\n" +
	"\x06global\x18\x03 \x01(\v2B.syncthing.config.v2.OptionsConfiguration.Network.Discovery.GlobalR\x06global\x1a\x95\x01\n" +
	"\x05Local\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x12\"\n" +
	"\tipv4_port\x18\x02 \x01(\x05:\x0521027R\bipv4Port\x12H\n" +
	"\x16ipv6_multicast_address\x18\x03 \x01(\t:\x12[ff12::8384]:21027R\x14ipv6MulticastAddress\x1a]\n" +
	"\x06Global\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x123\n" +
	"\aservers\x18\x02 \x01(\v2\x19.syncthing.config.v2.URLsR\aservers\x1a_\n" +
	"\x06Relays\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x125\n" +
	"\x14reconnect_interval_s\x18\x02 \x01(\x05:\x03600R\x12reconnectIntervalS\x1a\xd6\x01\n" +
	"\vAutoUpgrade\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x12/\n" +
	"\x10check_interval_s\x18\x02 \x01(\x05:\x0543200R\x0echeckIntervalS\x12-\n" +
	"\x12release_candidates\x18\x03 \x01(\bR\x11releaseCandidates\x12G\n" +
	"\n" +
	"server_url\x18\x04 \x01(\t:(https://upgrades.syncthing.net/meta.jsonR\tserverUrl\x1a\xd4\x01\n" +
	"\x0eUsageReporting\x12\x1e\n" +
	"\aenabled\x18\x01 \x01(\b:\x04trueR\aenabled\x12\x1b\n" +
	"\tunique_id\x18\x02 \x01(\tR\buniqueId\x124\n" +
	"\x03url\x18\x03 \x01(\t:\"https://data.syncthing.net/newdataR\x03url\x12,\n" +
	"\x0finitial_delay_s\x18\x04 \x01(\x05:\x041800R\rinitialDelayS\x12!\n" +
	"\ftls_insecure\x18\x05 \x01(\bR\vtlsInsecure\x1a5\n" +
	"\x05Audit\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\"T\n" +
	"\n" +
	"RateLimits\x12\"\n" +
	"\rmax_send_kbps\x18\x01 \x01(\x05R\vmaxSendKbps\x12\"\n" +
	"\rmax_recv_kbps\x18\x02 \x01(\x05R\vmaxRecvKbps\"\x1a\n" +
	"\x04URLs\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urlsB\xe6\x01\n" +
	"\x17com.syncthing.config.v2B\x19OptionsConfigurationProtoP\x01Z:github.com/syncthing/syncthing/internal/config/v2;configv2\xa2\x02\x03SCX\xaa\x02\x13Syncthing.Config.V2\xca\x02\x13Syncthing\\Config\\V2\xe2\x02\x1fSyncthing\\Config\\V2\\GPBMetadata\xea\x02\x15Syncthing::Config::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v2_options_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_config_v2_options_configuration_proto_goTypes = []any{
	(*OptionsConfiguration)(nil),                              // 0: syncthing.config.v2.OptionsConfiguration
	(*RateLimits)(nil),                                        // 1: syncthing.config.v2.RateLimits
	(*URLs)(nil),                                              // 2: syncthing.config.v2.URLs
	(*OptionsConfiguration_General)(nil),                      // 3: syncthing.config.v2.OptionsConfiguration.General
	(*OptionsConfiguration_Network)(nil),                      // 4: syncthing.config.v2.OptionsConfiguration.Network
	(*OptionsConfiguration_AutoUpgrade)(nil),                  // 5: syncthing.config.v2.OptionsConfiguration.AutoUpgrade
	(*OptionsConfiguration_UsageReporting)(nil),               // 6: syncthing.config.v2.OptionsConfiguration.UsageReporting
	(*OptionsConfiguration_Audit)(nil),                        // 7: syncthing.config.v2.OptionsConfiguration.Audit
	(*OptionsConfiguration_Network_ConnectionLimits)(nil),     // 8: syncthing.config.v2.OptionsConfiguration.Network.ConnectionLimits
	(*OptionsConfiguration_Network_ConnectionPriorities)(nil), // 9: syncthing.config.v2.OptionsConfiguration.Network.ConnectionPriorities
	(*OptionsConfiguration_Network_NAT)(nil),                  // 10: syncthing.config.v2.OptionsConfiguration.Network.NAT
	(*OptionsConfiguration_Network_Discovery)(nil),            // 11: syncthing.config.v2.OptionsConfiguration.Network.Discovery
	(*OptionsConfiguration_Network_Relays)(nil),               // 12: syncthing.config.v2.OptionsConfiguration.Network.Relays
	(*OptionsConfiguration_Network_Discovery_Local)(nil),      // 13: syncthing.config.v2.OptionsConfiguration.Network.Discovery.Local
	(*OptionsConfiguration_Network_Discovery_Global)(nil),     // 14: syncthing.config.v2.OptionsConfiguration.Network.Discovery.Global
}
var file_config_v2_options_configuration_proto_depIdxs = []int32{
	3,  // 0: syncthing.config.v2.OptionsConfiguration.general:type_name -> syncthing.config.v2.OptionsConfiguration.General
	4,  // 1: syncthing.config.v2.OptionsConfiguration.network:type_name -> syncthing.config.v2.OptionsConfiguration.Network
	5,  // 2: syncthing.config.v2.OptionsConfiguration.auto_upgrade:type_name -> syncthing.config.v2.OptionsConfiguration.AutoUpgrade
	6,  // 3: syncthing.config.v2.OptionsConfiguration.usage_reporting:type_name -> syncthing.config.v2.OptionsConfiguration.UsageReporting
	7,  // 4: syncthing.config.v2.OptionsConfiguration.audit:type_name -> syncthing.config.v2.OptionsConfiguration.Audit
	2,  // 5: syncthing.config.v2.OptionsConfiguration.Network.listen:type_name -> syncthing.config.v2.URLs
	1,  // 6: syncthing.config.v2.OptionsConfiguration.Network.rate_limits:type_name -> syncthing.config.v2.RateLimits
	8,  // 7: syncthing.config.v2.OptionsConfiguration.Network.connection_limits:type_name -> syncthing.config.v2.OptionsConfiguration.Network.ConnectionLimits
	9,  // 8: syncthing.config.v2.OptionsConfiguration.Network.connection_priorities:type_name -> syncthing.config.v2.OptionsConfiguration.Network.ConnectionPriorities
	10, // 9: syncthing.config.v2.OptionsConfiguration.Network.nat:type_name -> syncthing.config.v2.OptionsConfiguration.Network.NAT
	11, // 10: syncthing.config.v2.OptionsConfiguration.Network.discovery:type_name -> syncthing.config.v2.OptionsConfiguration.Network.Discovery
	12, // 11: syncthing.config.v2.OptionsConfiguration.Network.relays:type_name -> syncthing.config.v2.OptionsConfiguration.Network.Relays
	2,  // 12: syncthing.config.v2.OptionsConfiguration.Network.NAT.stun_servers:type_name -> syncthing.config.v2.URLs
	13, // 13: syncthing.config.v2.OptionsConfiguration.Network.Discovery.local:type_name -> syncthing.config.v2.OptionsConfiguration.Network.Discovery.Local
	14, // 14: syncthing.config.v2.OptionsConfiguration.Network.Discovery.global:type_name -> syncthing.config.v2.OptionsConfiguration.Network.Discovery.Global
	2,  // 15: syncthing.config.v2.OptionsConfiguration.Network.Discovery.Global.servers:type_name -> syncthing.config.v2.URLs
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_config_v2_options_configuration_proto_init() }
func file_config_v2_options_configuration_proto_init() {
	if File_config_v2_options_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v2_options_configuration_proto_rawDesc), len(file_config_v2_options_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v2_options_configuration_proto_goTypes,
		DependencyIndexes: file_config_v2_options_configuration_proto_depIdxs,
		MessageInfos:      file_config_v2_options_configuration_proto_msgTypes,
	}.Build()
	File_config_v2_options_configuration_proto = out.File
	file_config_v2_options_configuration_proto_goTypes = nil
	file_config_v2_options_configuration_proto_depIdxs = nil
}
