// @generated by protoc-gen-es v2.2.5
// @generated from file api/v2/config_service.proto (package api.v2, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Configuration } from "./config_resources_pb";

/**
 * Describes the file api/v2/config_service.proto.
 */
export declare const file_api_v2_config_service: GenFile;

/**
 * @generated from message api.v2.GetConfigurationRequest
 */
export declare type GetConfigurationRequest = Message<"api.v2.GetConfigurationRequest"> & {
};

/**
 * Describes the message api.v2.GetConfigurationRequest.
 * Use `create(GetConfigurationRequestSchema)` to create a new message.
 */
export declare const GetConfigurationRequestSchema: GenMessage<GetConfigurationRequest>;

/**
 * @generated from message api.v2.GetConfigurationResponse
 */
export declare type GetConfigurationResponse = Message<"api.v2.GetConfigurationResponse"> & {
  /**
   * @generated from field: api.v2.Configuration config = 1;
   */
  config?: Configuration;
};

/**
 * Describes the message api.v2.GetConfigurationResponse.
 * Use `create(GetConfigurationResponseSchema)` to create a new message.
 */
export declare const GetConfigurationResponseSchema: GenMessage<GetConfigurationResponse>;

/**
 * @generated from message api.v2.AddDeviceRequest
 */
export declare type AddDeviceRequest = Message<"api.v2.AddDeviceRequest"> & {
};

/**
 * Describes the message api.v2.AddDeviceRequest.
 * Use `create(AddDeviceRequestSchema)` to create a new message.
 */
export declare const AddDeviceRequestSchema: GenMessage<AddDeviceRequest>;

/**
 * @generated from message api.v2.AddDeviceResponse
 */
export declare type AddDeviceResponse = Message<"api.v2.AddDeviceResponse"> & {
};

/**
 * Describes the message api.v2.AddDeviceResponse.
 * Use `create(AddDeviceResponseSchema)` to create a new message.
 */
export declare const AddDeviceResponseSchema: GenMessage<AddDeviceResponse>;

/**
 * @generated from message api.v2.RemoveDeviceRequest
 */
export declare type RemoveDeviceRequest = Message<"api.v2.RemoveDeviceRequest"> & {
};

/**
 * Describes the message api.v2.RemoveDeviceRequest.
 * Use `create(RemoveDeviceRequestSchema)` to create a new message.
 */
export declare const RemoveDeviceRequestSchema: GenMessage<RemoveDeviceRequest>;

/**
 * @generated from message api.v2.RemoveDeviceResponse
 */
export declare type RemoveDeviceResponse = Message<"api.v2.RemoveDeviceResponse"> & {
};

/**
 * Describes the message api.v2.RemoveDeviceResponse.
 * Use `create(RemoveDeviceResponseSchema)` to create a new message.
 */
export declare const RemoveDeviceResponseSchema: GenMessage<RemoveDeviceResponse>;

/**
 * @generated from message api.v2.UpdateDeviceRequest
 */
export declare type UpdateDeviceRequest = Message<"api.v2.UpdateDeviceRequest"> & {
};

/**
 * Describes the message api.v2.UpdateDeviceRequest.
 * Use `create(UpdateDeviceRequestSchema)` to create a new message.
 */
export declare const UpdateDeviceRequestSchema: GenMessage<UpdateDeviceRequest>;

/**
 * @generated from message api.v2.UpdateDeviceResponse
 */
export declare type UpdateDeviceResponse = Message<"api.v2.UpdateDeviceResponse"> & {
};

/**
 * Describes the message api.v2.UpdateDeviceResponse.
 * Use `create(UpdateDeviceResponseSchema)` to create a new message.
 */
export declare const UpdateDeviceResponseSchema: GenMessage<UpdateDeviceResponse>;

/**
 * @generated from message api.v2.AddFolderRequest
 */
export declare type AddFolderRequest = Message<"api.v2.AddFolderRequest"> & {
};

/**
 * Describes the message api.v2.AddFolderRequest.
 * Use `create(AddFolderRequestSchema)` to create a new message.
 */
export declare const AddFolderRequestSchema: GenMessage<AddFolderRequest>;

/**
 * @generated from message api.v2.AddFolderResponse
 */
export declare type AddFolderResponse = Message<"api.v2.AddFolderResponse"> & {
};

/**
 * Describes the message api.v2.AddFolderResponse.
 * Use `create(AddFolderResponseSchema)` to create a new message.
 */
export declare const AddFolderResponseSchema: GenMessage<AddFolderResponse>;

/**
 * @generated from message api.v2.RemoveFolderRequest
 */
export declare type RemoveFolderRequest = Message<"api.v2.RemoveFolderRequest"> & {
};

/**
 * Describes the message api.v2.RemoveFolderRequest.
 * Use `create(RemoveFolderRequestSchema)` to create a new message.
 */
export declare const RemoveFolderRequestSchema: GenMessage<RemoveFolderRequest>;

/**
 * @generated from message api.v2.RemoveFolderResponse
 */
export declare type RemoveFolderResponse = Message<"api.v2.RemoveFolderResponse"> & {
};

/**
 * Describes the message api.v2.RemoveFolderResponse.
 * Use `create(RemoveFolderResponseSchema)` to create a new message.
 */
export declare const RemoveFolderResponseSchema: GenMessage<RemoveFolderResponse>;

/**
 * @generated from message api.v2.UpdateFolderRequest
 */
export declare type UpdateFolderRequest = Message<"api.v2.UpdateFolderRequest"> & {
};

/**
 * Describes the message api.v2.UpdateFolderRequest.
 * Use `create(UpdateFolderRequestSchema)` to create a new message.
 */
export declare const UpdateFolderRequestSchema: GenMessage<UpdateFolderRequest>;

/**
 * @generated from message api.v2.UpdateFolderResponse
 */
export declare type UpdateFolderResponse = Message<"api.v2.UpdateFolderResponse"> & {
};

/**
 * Describes the message api.v2.UpdateFolderResponse.
 * Use `create(UpdateFolderResponseSchema)` to create a new message.
 */
export declare const UpdateFolderResponseSchema: GenMessage<UpdateFolderResponse>;

/**
 * @generated from service api.v2.ConfigurationService
 */
export declare const ConfigurationService: GenService<{
  /**
   * @generated from rpc api.v2.ConfigurationService.GetConfiguration
   */
  getConfiguration: {
    methodKind: "unary";
    input: typeof GetConfigurationRequestSchema;
    output: typeof GetConfigurationResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.AddDevice
   */
  addDevice: {
    methodKind: "unary";
    input: typeof AddDeviceRequestSchema;
    output: typeof AddDeviceResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.RemoveDevice
   */
  removeDevice: {
    methodKind: "unary";
    input: typeof RemoveDeviceRequestSchema;
    output: typeof RemoveDeviceResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.UpdateDevice
   */
  updateDevice: {
    methodKind: "unary";
    input: typeof UpdateDeviceRequestSchema;
    output: typeof UpdateDeviceResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.AddFolder
   */
  addFolder: {
    methodKind: "unary";
    input: typeof AddFolderRequestSchema;
    output: typeof AddFolderResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.RemoveFolder
   */
  removeFolder: {
    methodKind: "unary";
    input: typeof RemoveFolderRequestSchema;
    output: typeof RemoveFolderResponseSchema;
  },
  /**
   * @generated from rpc api.v2.ConfigurationService.UpdateFolder
   */
  updateFolder: {
    methodKind: "unary";
    input: typeof UpdateFolderRequestSchema;
    output: typeof UpdateFolderResponseSchema;
  },
}>;

