// @generated by protoc-gen-es v2.2.5
// @generated from file api/v2/config_service.proto (package api.v2, edition 2023)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_api_v2_config_resources } from "./config_resources_pb";
import { file_google_protobuf_go_features } from "../../google/protobuf/go_features_pb";

/**
 * Describes the file api/v2/config_service.proto.
 */
export const file_api_v2_config_service = /*@__PURE__*/
  fileDesc("ChthcGkvdjIvY29uZmlnX3NlcnZpY2UucHJvdG8SBmFwaS52MiIZChdHZXRDb25maWd1cmF0aW9uUmVxdWVzdCJBChhHZXRDb25maWd1cmF0aW9uUmVzcG9uc2USJQoGY29uZmlnGAEgASgLMhUuYXBpLnYyLkNvbmZpZ3VyYXRpb24iEgoQQWRkRGV2aWNlUmVxdWVzdCITChFBZGREZXZpY2VSZXNwb25zZSIVChNSZW1vdmVEZXZpY2VSZXF1ZXN0IhYKFFJlbW92ZURldmljZVJlc3BvbnNlIhUKE1VwZGF0ZURldmljZVJlcXVlc3QiFgoUVXBkYXRlRGV2aWNlUmVzcG9uc2UiEgoQQWRkRm9sZGVyUmVxdWVzdCITChFBZGRGb2xkZXJSZXNwb25zZSIVChNSZW1vdmVGb2xkZXJSZXF1ZXN0IhYKFFJlbW92ZUZvbGRlclJlc3BvbnNlIhUKE1VwZGF0ZUZvbGRlclJlcXVlc3QiFgoUVXBkYXRlRm9sZGVyUmVzcG9uc2UyqwQKFENvbmZpZ3VyYXRpb25TZXJ2aWNlElcKEEdldENvbmZpZ3VyYXRpb24SHy5hcGkudjIuR2V0Q29uZmlndXJhdGlvblJlcXVlc3QaIC5hcGkudjIuR2V0Q29uZmlndXJhdGlvblJlc3BvbnNlIgASQgoJQWRkRGV2aWNlEhguYXBpLnYyLkFkZERldmljZVJlcXVlc3QaGS5hcGkudjIuQWRkRGV2aWNlUmVzcG9uc2UiABJLCgxSZW1vdmVEZXZpY2USGy5hcGkudjIuUmVtb3ZlRGV2aWNlUmVxdWVzdBocLmFwaS52Mi5SZW1vdmVEZXZpY2VSZXNwb25zZSIAEksKDFVwZGF0ZURldmljZRIbLmFwaS52Mi5VcGRhdGVEZXZpY2VSZXF1ZXN0GhwuYXBpLnYyLlVwZGF0ZURldmljZVJlc3BvbnNlIgASQgoJQWRkRm9sZGVyEhguYXBpLnYyLkFkZEZvbGRlclJlcXVlc3QaGS5hcGkudjIuQWRkRm9sZGVyUmVzcG9uc2UiABJLCgxSZW1vdmVGb2xkZXISGy5hcGkudjIuUmVtb3ZlRm9sZGVyUmVxdWVzdBocLmFwaS52Mi5SZW1vdmVGb2xkZXJSZXNwb25zZSIAEksKDFVwZGF0ZUZvbGRlchIbLmFwaS52Mi5VcGRhdGVGb2xkZXJSZXF1ZXN0GhwuYXBpLnYyLlVwZGF0ZUZvbGRlclJlc3BvbnNlIgBCmwEKCmNvbS5hcGkudjJCEkNvbmZpZ1NlcnZpY2VQcm90b1ABWjhnaXRodWIuY29tL3N5bmN0aGluZy9zeW5jdGhpbmcvaW50ZXJuYWwvZ2VuL2FwaS92MjthcGl2MqICA0FYWKoCBkFwaS5WMsoCBkFwaVxWMuICEkFwaVxWMlxHUEJNZXRhZGF0YeoCB0FwaTo6VjKSAwXSPgIQA2IIZWRpdGlvbnNw6Ac", [file_api_v2_config_resources, file_google_protobuf_go_features]);

/**
 * Describes the message api.v2.GetConfigurationRequest.
 * Use `create(GetConfigurationRequestSchema)` to create a new message.
 */
export const GetConfigurationRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 0);

/**
 * Describes the message api.v2.GetConfigurationResponse.
 * Use `create(GetConfigurationResponseSchema)` to create a new message.
 */
export const GetConfigurationResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 1);

/**
 * Describes the message api.v2.AddDeviceRequest.
 * Use `create(AddDeviceRequestSchema)` to create a new message.
 */
export const AddDeviceRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 2);

/**
 * Describes the message api.v2.AddDeviceResponse.
 * Use `create(AddDeviceResponseSchema)` to create a new message.
 */
export const AddDeviceResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 3);

/**
 * Describes the message api.v2.RemoveDeviceRequest.
 * Use `create(RemoveDeviceRequestSchema)` to create a new message.
 */
export const RemoveDeviceRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 4);

/**
 * Describes the message api.v2.RemoveDeviceResponse.
 * Use `create(RemoveDeviceResponseSchema)` to create a new message.
 */
export const RemoveDeviceResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 5);

/**
 * Describes the message api.v2.UpdateDeviceRequest.
 * Use `create(UpdateDeviceRequestSchema)` to create a new message.
 */
export const UpdateDeviceRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 6);

/**
 * Describes the message api.v2.UpdateDeviceResponse.
 * Use `create(UpdateDeviceResponseSchema)` to create a new message.
 */
export const UpdateDeviceResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 7);

/**
 * Describes the message api.v2.AddFolderRequest.
 * Use `create(AddFolderRequestSchema)` to create a new message.
 */
export const AddFolderRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 8);

/**
 * Describes the message api.v2.AddFolderResponse.
 * Use `create(AddFolderResponseSchema)` to create a new message.
 */
export const AddFolderResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 9);

/**
 * Describes the message api.v2.RemoveFolderRequest.
 * Use `create(RemoveFolderRequestSchema)` to create a new message.
 */
export const RemoveFolderRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 10);

/**
 * Describes the message api.v2.RemoveFolderResponse.
 * Use `create(RemoveFolderResponseSchema)` to create a new message.
 */
export const RemoveFolderResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 11);

/**
 * Describes the message api.v2.UpdateFolderRequest.
 * Use `create(UpdateFolderRequestSchema)` to create a new message.
 */
export const UpdateFolderRequestSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 12);

/**
 * Describes the message api.v2.UpdateFolderResponse.
 * Use `create(UpdateFolderResponseSchema)` to create a new message.
 */
export const UpdateFolderResponseSchema = /*@__PURE__*/
  messageDesc(file_api_v2_config_service, 13);

/**
 * @generated from service api.v2.ConfigurationService
 */
export const ConfigurationService = /*@__PURE__*/
  serviceDesc(file_api_v2_config_service, 0);

