// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lib/model/candidate.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SharingDeviceEntry struct {
	Device []byte `protobuf:"bytes,1,opt,name=device,proto3" json:"device" xml:"device"`
	When   int64  `protobuf:"varint,2,opt,name=when,proto3" json:"when" xml:"when"`
}

func (m *SharingDeviceEntry) Reset()         { *m = SharingDeviceEntry{} }
func (m *SharingDeviceEntry) String() string { return proto.CompactTextString(m) }
func (*SharingDeviceEntry) ProtoMessage()    {}
func (*SharingDeviceEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d5d4daefc0f51, []int{0}
}
func (m *SharingDeviceEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SharingDeviceEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SharingDeviceEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SharingDeviceEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingDeviceEntry.Merge(m, src)
}
func (m *SharingDeviceEntry) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SharingDeviceEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingDeviceEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SharingDeviceEntry proto.InternalMessageInfo

type SharingFolderEntry struct {
	Folder  string               `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder" xml:"folder"`
	Devices []SharingDeviceEntry `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices" xml:"device"`
}

func (m *SharingFolderEntry) Reset()         { *m = SharingFolderEntry{} }
func (m *SharingFolderEntry) String() string { return proto.CompactTextString(m) }
func (*SharingFolderEntry) ProtoMessage()    {}
func (*SharingFolderEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d5d4daefc0f51, []int{1}
}
func (m *SharingFolderEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SharingFolderEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SharingFolderEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SharingFolderEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingFolderEntry.Merge(m, src)
}
func (m *SharingFolderEntry) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SharingFolderEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingFolderEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SharingFolderEntry proto.InternalMessageInfo

type SharingCandidates struct {
	Folders []SharingFolderEntry `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders" xml:"folder"`
}

func (m *SharingCandidates) Reset()         { *m = SharingCandidates{} }
func (m *SharingCandidates) String() string { return proto.CompactTextString(m) }
func (*SharingCandidates) ProtoMessage()    {}
func (*SharingCandidates) Descriptor() ([]byte, []int) {
	return fileDescriptor_b40d5d4daefc0f51, []int{2}
}
func (m *SharingCandidates) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SharingCandidates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SharingCandidates.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SharingCandidates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingCandidates.Merge(m, src)
}
func (m *SharingCandidates) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SharingCandidates) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingCandidates.DiscardUnknown(m)
}

var xxx_messageInfo_SharingCandidates proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SharingDeviceEntry)(nil), "model.SharingDeviceEntry")
	proto.RegisterType((*SharingFolderEntry)(nil), "model.SharingFolderEntry")
	proto.RegisterType((*SharingCandidates)(nil), "model.SharingCandidates")
}

func init() { proto.RegisterFile("lib/model/candidate.proto", fileDescriptor_b40d5d4daefc0f51) }

var fileDescriptor_b40d5d4daefc0f51 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xed, 0x16, 0x8a, 0x30, 0x5d, 0xc8, 0x80, 0x52, 0x06, 0xbb, 0xf2, 0x14, 0x31, 0xa4,
	0x52, 0xd9, 0x18, 0xc3, 0xcf, 0xc0, 0x58, 0x98, 0xd8, 0xda, 0xc4, 0x34, 0x96, 0x12, 0x07, 0x25,
	0xe6, 0xa7, 0x6f, 0xc1, 0x13, 0x20, 0x1e, 0x27, 0x63, 0x46, 0x26, 0x4b, 0x6d, 0xb6, 0x8c, 0x7d,
	0x02, 0x54, 0x3b, 0x09, 0x95, 0xc2, 0x96, 0x73, 0x6e, 0x8e, 0xbe, 0x7b, 0x7c, 0xd1, 0x28, 0xe2,
	0x8b, 0x49, 0x9c, 0x04, 0x2c, 0x9a, 0xf8, 0x73, 0x11, 0xf0, 0x60, 0x2e, 0x99, 0xfb, 0x92, 0x26,
	0x32, 0xb1, 0x0e, 0xb5, 0x4d, 0x25, 0xb2, 0x1e, 0xc2, 0x79, 0xca, 0xc5, 0xf2, 0x86, 0xbd, 0x71,
	0x9f, 0xdd, 0x0a, 0x99, 0xae, 0xac, 0x29, 0x1a, 0x04, 0x5a, 0xda, 0x70, 0x0c, 0x9d, 0xa1, 0x77,
	0x5e, 0x29, 0x52, 0x3b, 0x5b, 0x45, 0x86, 0x1f, 0x71, 0x74, 0x45, 0x8d, 0xa4, 0xb3, 0xda, 0xb7,
	0x2e, 0xd0, 0xc1, 0x7b, 0xc8, 0x84, 0xdd, 0x1b, 0x43, 0xa7, 0xef, 0x9d, 0x55, 0x8a, 0x68, 0xbd,
	0x55, 0x04, 0xe9, 0xff, 0x77, 0x82, 0xce, 0xb4, 0x47, 0xbf, 0x60, 0x8b, 0xbd, 0x4b, 0xa2, 0x80,
	0xa5, 0x2d, 0xf6, 0x59, 0x4b, 0x8d, 0x3d, 0x36, 0x58, 0xe3, 0xb4, 0x58, 0x23, 0xe9, 0xac, 0xf6,
	0xad, 0x47, 0x74, 0x64, 0x16, 0xc8, 0xec, 0xde, 0xb8, 0xef, 0x9c, 0x4c, 0x47, 0xae, 0x6e, 0xe6,
	0x76, 0x6b, 0x79, 0x24, 0x57, 0x04, 0x54, 0x8a, 0x34, 0x89, 0x4e, 0x97, 0x66, 0x40, 0x39, 0x3a,
	0xad, 0xf3, 0xd7, 0xcd, 0xbb, 0x65, 0x3b, 0x94, 0x81, 0x66, 0x36, 0xfc, 0x0f, 0xb5, 0x57, 0xe5,
	0x0f, 0x55, 0x27, 0x3a, 0xfb, 0x37, 0x03, 0xef, 0x3e, 0x5f, 0x63, 0x50, 0xac, 0x31, 0xc8, 0x37,
	0x18, 0x16, 0x1b, 0x0c, 0x3f, 0x4b, 0x0c, 0xbe, 0x4b, 0x0c, 0x8b, 0x12, 0x83, 0x9f, 0x12, 0x83,
	0x27, 0x67, 0xc9, 0x65, 0xf8, 0xba, 0x70, 0xfd, 0x24, 0x9e, 0x64, 0x2b, 0xe1, 0xcb, 0x90, 0x8b,
	0xe5, 0xde, 0x57, 0x7b, 0xe4, 0xc5, 0x40, 0xdf, 0xf6, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0x3e, 0x14, 0xcc, 0xf8, 0x01, 0x00, 0x00,
}

func (m *SharingDeviceEntry) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SharingDeviceEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SharingDeviceEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.When != 0 {
		i = encodeVarintCandidate(dAtA, i, uint64(m.When))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Device) > 0 {
		i -= len(m.Device)
		copy(dAtA[i:], m.Device)
		i = encodeVarintCandidate(dAtA, i, uint64(len(m.Device)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SharingFolderEntry) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SharingFolderEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SharingFolderEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Devices) > 0 {
		for iNdEx := len(m.Devices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Devices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCandidate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Folder) > 0 {
		i -= len(m.Folder)
		copy(dAtA[i:], m.Folder)
		i = encodeVarintCandidate(dAtA, i, uint64(len(m.Folder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SharingCandidates) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SharingCandidates) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SharingCandidates) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Folders) > 0 {
		for iNdEx := len(m.Folders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Folders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCandidate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintCandidate(dAtA []byte, offset int, v uint64) int {
	offset -= sovCandidate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SharingDeviceEntry) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Device)
	if l > 0 {
		n += 1 + l + sovCandidate(uint64(l))
	}
	if m.When != 0 {
		n += 1 + sovCandidate(uint64(m.When))
	}
	return n
}

func (m *SharingFolderEntry) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Folder)
	if l > 0 {
		n += 1 + l + sovCandidate(uint64(l))
	}
	if len(m.Devices) > 0 {
		for _, e := range m.Devices {
			l = e.ProtoSize()
			n += 1 + l + sovCandidate(uint64(l))
		}
	}
	return n
}

func (m *SharingCandidates) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Folders) > 0 {
		for _, e := range m.Folders {
			l = e.ProtoSize()
			n += 1 + l + sovCandidate(uint64(l))
		}
	}
	return n
}

func sovCandidate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCandidate(x uint64) (n int) {
	return sovCandidate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SharingDeviceEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharingDeviceEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharingDeviceEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Device", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCandidate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCandidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Device = append(m.Device[:0], dAtA[iNdEx:postIndex]...)
			if m.Device == nil {
				m.Device = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field When", wireType)
			}
			m.When = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.When |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCandidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SharingFolderEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharingFolderEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharingFolderEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Folder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCandidate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCandidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Folder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Devices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCandidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCandidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Devices = append(m.Devices, SharingDeviceEntry{})
			if err := m.Devices[len(m.Devices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCandidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SharingCandidates) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCandidate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SharingCandidates: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SharingCandidates: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Folders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCandidate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCandidate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Folders = append(m.Folders, SharingFolderEntry{})
			if err := m.Folders[len(m.Folders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCandidate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCandidate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCandidate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCandidate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCandidate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCandidate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCandidate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCandidate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCandidate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCandidate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCandidate = fmt.Errorf("proto: unexpected end of group")
)
