// Copyright (C) 2026 The Syncthing Authors.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this file,
// You can obtain one at https://mozilla.org/MPL/2.0/.

//go:build integration

package integration

import (
	"fmt"
	"testing"
)

// TestSyncAtoB starts two Syncthing instances backed by an in-memory
// fakefs, wires them together via an API config push on each side, and
// verifies that the files generated by fakefs on instance A sync across
// to instance B.
func TestSyncAtoB(t *testing.T) {
	const numFiles = 1000

	a := newInstance(t, 1, fmt.Sprintf("a?files=%d&sizeavg=4096&seed=1", numFiles))
	b := newInstance(t, 2, "b")

	a.start(t)
	b.start(t)

	a.connectTo(t, b)
	b.connectTo(t, a)

	awaitSync(t, "default", a.process, b.process)

	model, err := b.process.Model("default")
	if err != nil {
		t.Fatal(err)
	}
	if model.LocalFiles != numFiles {
		t.Fatalf("instance b ended up with %d files, want %d", model.LocalFiles, numFiles)
	}
	if model.NeedFiles != 0 {
		t.Fatalf("instance b still needs %d files", model.NeedFiles)
	}
}
