name: Run issue metadata jobs

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:

  #
  # golangci-lint runs a suite of static analysis checks on the code
  #

  golangci:
    runs-on: ubuntu-latest
    name: Golangci-lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: ensure asset generation
        run: go run build.go assets

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true

  #
  # Meta checks for formatting, copyright, etc
  #

  meta:
    name: Meta checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: |
          go run build.go assets
          go test -v ./meta

  #
  # Set labels on PRs, which are used to categorise release notes
  #

  labels:
    name: Set labels
    runs-on: ubuntu-latest
    steps:
    - uses: srvaroa/labeler@v1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
